privacy-scaling-explorations/zkevm-circuits

src/state_circuit/memory.rs

Two memory checks added - whether the initial state is ok and whether the value that is read is the same as the value that was written at the same address.

Two initial checks added

---

src/gadget.rs
src/gadget/monotone.rs

In memory circuit, we need to check if `gc` are strict-monotone in the same `address`. And `gc` has some not too large maximum value so we can be sure diff of each two adjacent row will not exceed the maximum (I call `RANGE` here). (#7)
In this gadget, we pass a advice column for check, with a function returning any expression to play as a switch of this gadget. In this way, we can use `is_equal_rot`'s expression to check if `gc` are strict-monotone when `address === address_prev`.
Also the gadget has three const-generic parameters `RANGE`, `INCR` and `STRICT` for flexibility.
- `RANGE` - specifying the maximum the diff could be
- `INCR` - should be monotone increasing or monotone decreasing (`q_enable` always specify `Rotation::cur()` and compare to `Rotation::prev()`)
- `STRICT` - …

Implement gadget monotone

---

src/gadget.rs
src/gadget/is_zero.rs

In memory circuit, we need to check if `gc` are strict-monotone in the same memory address. At the same time, we have to escape the init row of different memory key (also for stack key). So we need a gadget to help enable `gc`'s monotone check when `is_zero(address - address_prev)`. (#8)
Another example, we might need to check if a witness `op` is equal to another fixed column and enable custom constraint in evm circuit, and we can use `is_zero(op - f_op)` to help.
In this gadget, we need a column to let prover to witness the inverse of `value_diff` or zero if no inverse, which gives us a bool expression indicating that `is_zero(value_diff)` by `1 - value_diff ⋅ value_diff.invert_or_zero()`
For flexibility, the gadget allows parent circuit to pass `value_diff` by expression, which can …

Implement gadget is_zero

---

Cargo.toml
src/gadget/is_zero.rs
src/gadget/monotone.rs
src/state_circuit/memory.rs

This brings in the `SimpleFloorPlanner` and changes the `Circuit` trait.
This also updates the public inputs API, which is the main motivation
for bumping the commit. (This change will not be noticeable in this diff
since our codebase does not currently use public inputs.)
This also brings in zero-knowledge blinding factors; however, we
will fork those out in a future commit.

Bump halo2 commit

---

Makefile

With this we can easily run all the checks enforced by GH's CI locally
preventing to run the CI for things that are not going to pass anyway.
Resolves: #30

Add Makefile to crate

---

bus-mapping/Cargo.toml
bus-mapping/README.md
bus-mapping/src/error.rs
bus-mapping/src/evm.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/exec_trace/exec_step.rs
bus-mapping/src/lib.rs
bus-mapping/src/operation.rs
bus-mapping/src/operation/container.rs

- Add an API to collect sorted Mem/Stack/Storage Operations 
- Add an API to fetch Container ops from refs
- Add getters for Stack/Storage & Memory ops in trace
Closes: #35

ExecutionTrace API extension

---

bus-mapping/src/evm.rs

As suggested by @miha-stopar. Until we don't have the specific Scalar/Field structs we're going to be using, we need to deal with `EvmWord`-like structs which are nothing else than a wrapper over `BigUint`.
Therefore, we at least should provide a way to convert these `EvmWord`s into byte arrays so that we can do tmp conversions.

Implement byte-conversion for `EvmWord` & `MemoryAddress`

---

bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/push.rs

As discussed with @han0110 we should externalize all of
the Constraint-System/circuit related stuff to zkevm-circuits
in order to reduce circular depency issuesand make
the overall solution simpler.
Resolves: #49

Externalize Circuit-related logic to zkevm-circuits

---

bus-mapping/src/error.rs
bus-mapping/src/evm.rs
bus-mapping/src/evm/opcodes/ids.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/lib.rs
bus-mapping/src/operation/container.rs
zkevm-circuits/src/lib.rs

Remove the `broken_intra_doc_links ` warning and fix some typos.

Remove warning and fix some typos

---

Cargo.toml
bus-mapping/src/evm.rs
bus-mapping/src/evm/gas.rs
bus-mapping/src/evm/opcodes/ids.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/operation.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/op_execution.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic.rs
zkevm-circuits/src/evm_circuit/op_execution/comparator.rs
zkevm-circuits/src/evm_circuit/op_execution/push.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/lib.rs
zkevm-circuits/src/util.rs

This PR aims to provides:
1. A flexible design of evm circuit
2. A trait for op gadget for us to implmenent without caring about the actual circuit layout
3. An example `AddGadget` for reference (Closes #9)
Todo:

EVM Circuit and trait OpGadget

---

README.md

We originally started wtih a hackmd for spec. After we moved the spec to github. Just updateing the readme to point to the new spec.

Update README.md to point to spec repo

---

bus-mapping/src/evm.rs
bus-mapping/src/evm/memory.rs
bus-mapping/src/evm/opcodes/mload.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/exec_trace/exec_step.rs
bus-mapping/src/exec_trace/parsing.rs
bus-mapping/src/macros.rs
bus-mapping/src/operation.rs
zkevm-circuits/src/state_circuit/state.rs

While keeping the compatibility between bytes and `EvmWord` the `Memory`
will not work based on bytes internally to allow for unaligned memory
read and write operations which are required by some Opcodes.
- Change Memory layout to wrap over `Vec<u8>` instead of `Vec<EvmWord>`.
- Implement Indexing operations over Memory via `MemoryAddress`.
- Implement/derive arithmetic ops for `MemoryAddress`.
- Change `MemoryOp` to contain as value `Vec<u8>`.
- Refactor tests in order to create the `Memory` instances on the new
way required.
Resolves: #33

Change Memory layout to be byte-based 

---

.github/labeler.yml
.github/release-drafter.yml
.github/workflows/draft.yml
.github/workflows/labeler.yml

We want to cut releases for the repo so that people working on the testing have some versions to track.
It would be great to inform in the release draft that what features or changes we added in that release
1. We use the auto labeler to label PRs that are related to "zkevm-circuit" (core-API), "opcodes", "busmapping", or "keccak".
2. We use the release drafter to automatically generate reports that sort PRs under each label.
Example release would look like this https://github.com/thehubbleproject/hubble-contracts/releases/tag/v0.10.0

Labeler and release draft

---

.github/labeler.yml

Due to the wrong path regex, the labeler can't correctly label `zkevm-circuits` and `opcode`
Fix the path regex

add missing src

---

.github/workflows/draft.yml

The wrong branch is configured so that the release drafter is never triggered.
My bad, sorry 🙈 .

fix release drafter

---

zkevm-circuits/src/evm_circuit/op_execution.rs
zkevm-circuits/src/evm_circuit/op_execution/byte.rs
zkevm-circuits/src/evm_circuit/op_execution/comparator.rs
zkevm-circuits/src/evm_circuit/op_execution/utils.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/math_gadgets.rs
zkevm-circuits/src/evm_circuit/param.rs

Good/bad idea? I would think this is more efficient than having a separate gadget because this only adds a few expressions to `LtGadget`. Also not 100% sure this works correctly, so would like to know from the original implementors if there may be some unexpected problems with doing EQ like this.
Tried to keep the diff minimal to show only the necessary changes for EQ support, so did not do anything else (like use `ConstraintBuilder`).
Also fixed a small issue with the tests where the trace was incorrectly built.

Add EQ support in LtGadget

---

bus-mapping/src/evm.rs
bus-mapping/src/evm/opcodes/ids.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic.rs
zkevm-circuits/src/evm_circuit/op_execution/byte.rs
zkevm-circuits/src/evm_circuit/op_execution/comparator.rs
zkevm-circuits/src/evm_circuit/op_execution/dup.rs
zkevm-circuits/src/evm_circuit/op_execution/jumpdest.rs
zkevm-circuits/src/evm_circuit/op_execution/pc.rs
zkevm-circuits/src/evm_circuit/op_execution/pop.rs
zkevm-circuits/src/evm_circuit/op_execution/push.rs
zkevm-circuits/src/evm_circuit/op_execution/signextend.rs
zkevm-circuits/src/evm_circuit/op_execution/swap.rs
zkevm-circuits/src/evm_circuit/op_execution/utils.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/common_cases.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/constraint_builder.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/math_gadgets.rs

Updated all opcodes implementations to use all the utilities we currently have available that did not already do so. Unfortunately this makes for a large diff but better earlier than later I think. The comparator gadget was already updated in #120 so did not update it again here.
All implementations should be identical to the previous version. If you find a change it's very likely I made a mistake in the conversion. I did do a small change in `push.rs` lines 75..91 because I think there was an issue there (did not check the MSB selector) but maybe I misunderstood something.

Refactor all opcodes to use the constraint builder + other utils

---

bus-mapping/src/evm.rs
bus-mapping/src/evm/gas.rs
bus-mapping/src/evm/opcodes/mload.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/op_execution.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic.rs
zkevm-circuits/src/evm_circuit/op_execution/byte.rs
zkevm-circuits/src/evm_circuit/op_execution/comparator.rs
zkevm-circuits/src/evm_circuit/op_execution/dup.rs
zkevm-circuits/src/evm_circuit/op_execution/jumpdest.rs
zkevm-circuits/src/evm_circuit/op_execution/memory.rs
zkevm-circuits/src/evm_circuit/op_execution/pc.rs
zkevm-circuits/src/evm_circuit/op_execution/pop.rs
zkevm-circuits/src/evm_circuit/op_execution/push.rs
zkevm-circuits/src/evm_circuit/op_execution/signextend.rs
zkevm-circuits/src/evm_circuit/op_execution/swap.rs
zkevm-circuits/src/evm_circuit/op_execution/utils.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/common_cases.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/constraint_builder.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/math_gadgets.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/memory_gadgets.rs
zkevm-circuits/src/evm_circuit/param.rs

Spec: https://github.com/appliedzkp/zkevm-specs/pull/61
Currently the value ranges in the memory size/cost calculations can get quite big because of no early range limitation (except only using the 5 LSBs of the address). Perhaps an earlier check that limits the size a little bit more earlier could save a couple of lookups. But let me know what you think of the current implementation. The testing is also quite limited for now because it's currently not easy to verify all the values against expected ones.
Does not currently implement `MSTORE8`. My idea is to implement this opcode in the same `MemoryGadget` because very few changes are needed. The only challenge is that ideally we can just do the 32 memory lookups to the same single memory write in the busmapping, but for that I need to be …

Implement MLOAD/MSTORE opcodes

---

.cargo/config.toml

The command `cargo test -p bus-mapping` failed on Apple M1 with the following error messages
```
= note: Undefined symbols for architecture arm64:
"_CFStringCreateWithBytes", referenced from:
_crypto/x509/internal/macos.x509_CFStringCreateWithBytes_trampoline in libgeth_utils-614fa87fc478fa6f.rlib(go.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This is the same issue as #131's. But the solution in #131 only includes the `x86_64` version of macOS.
Apply the config to all macOS

build gethutils for apple silicon

---

bus-mapping/Cargo.toml
bus-mapping/src/error.rs
bus-mapping/src/eth_types.rs
bus-mapping/src/lib.rs
bus-mapping/src/rpc.rs

Introduce a generic struct which holds a `Provider` (can be Http, Ws,
Ipc) which will be used to make any calls/requests to Geth.
Since the `json_rpc` lib that we use requires the response types to be:
`Serialize + Deserialize`, it has been needed to impl `Serialize` for
the types that were lacking it.
- GethExecStepInternal now derives `Serialize`.
- Implemented `From<GethExecStep> for GethExecStepInternal` which is
used in the next point.
- Implement `Serialize` for `GethExecStep` serializing it as a
`GethExecStepInternal` using the previous `From` impl mentioned.
Geth return value for `debug_traceBlockByHash` and
`debug_traceBlockByNumber` isn't the expected.
While the expected format was to get from these calls
`Vec<GethExecTrace>`, you are given a similar vector but that contains a …

Add GethClient and support for minimum required JSON-RPC endpoints by bus-mapping.

---

bus-mapping/Cargo.toml
bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/error.rs
bus-mapping/src/evm/opcodes/sload.rs

Add the required fields in the CallContext, and use it to detect
CREATE/CREATE2 RETURN errors, and to fill the address in SLOAD
StorageOp.
Resolve https://github.com/appliedzkp/zkevm-circuits/issues/137
Resolve https://github.com/appliedzkp/zkevm-circuits/issues/185

bus-mapping: Extend CallContext

---

zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic/add.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic/bitwise.rs
zkevm-circuits/src/evm_circuit/op_execution/byte.rs
zkevm-circuits/src/evm_circuit/op_execution/comparator.rs
zkevm-circuits/src/evm_circuit/op_execution/dup.rs
zkevm-circuits/src/evm_circuit/op_execution/jumpdest.rs
zkevm-circuits/src/evm_circuit/op_execution/memory.rs
zkevm-circuits/src/evm_circuit/op_execution/pc.rs
zkevm-circuits/src/evm_circuit/op_execution/pop.rs
zkevm-circuits/src/evm_circuit/op_execution/push.rs
zkevm-circuits/src/evm_circuit/op_execution/signextend.rs
zkevm-circuits/src/evm_circuit/op_execution/swap.rs

This PR aims to mitigate the long testing time due to large table required by bitwise opcode gadget. It adds a flag `including_large_tables` when `load_fixed_tables` to decide if to include large table or not.

Mitigate the long testing time by allowing partial fixed table

---

bus-mapping/src/eth_types.rs
bus-mapping/src/lib.rs
bus-mapping/src/statedb.rs

This is a small PR to introduce the StateDB key-value database that will be used in the `CircuitInputBuilder`.   It's not yet integrated because in order to use it in the `CircuitInputBuilder` we first need to fill this database with results from geth, but we don't have the methods yet, and we also need to keep track of all state operations to know what to query from geth.
Resolve https://github.com/appliedzkp/zkevm-circuits/issues/184

bus-mapping: Add StateDB key-value database

---

bus-mapping/Cargo.toml
bus-mapping/src/eth_types.rs

Remove unecessary Serialize implementations for types used in rpc
results
Resolve https://github.com/appliedzkp/zkevm-circuits/issues/179

bus-mapping: Bump ethers dependency

---

bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/eth_types.rs
bus-mapping/src/evm/memory.rs
bus-mapping/src/evm/stack.rs
bus-mapping/src/evm/storage.rs

Generate a trace of state accesses from a transaction execution trace.
From a state access trace, generate a state access set.
The AccessSet will be used to query necessary State data from geth to
process transactions and generate the associated circuit inputs.
Note that although similar in concept to the `AccessList`, this is not the same.  This information is not for the circuit nor to compute gas costs of cold/warm accesses.  It's to know what to query about the state in Geth in order to fill the StateDB (and later the partial state trie) for the CircuitInputBuilder to do its job.

Generate AccessTrace and AccessSet

---

circuit-benchmarks/.gitignore

currently circuit-benchmarks/src/bench_params.rs (if ever generated) will be easily added to git by mistake. But this should depend on the ENV config of different people

gitignore circuit_benchmarks bench_params

---

keccak256/src/gates/pi.rs

we don't need 25 columns for the pi gate.
We can use a function that takes input [(Cell, F); 25] and output [(Cell, F); 25]. Permute them at the right order. The copy constraint in the next gate will enforce what Pi intended to do.

Radical Pi Gate

---

keccak256/src/gates/absorb.rs
keccak256/src/gates/iota_b13.rs
keccak256/src/gates/iota_b9.rs
keccak256/src/gates/mixing.rs

Change Iotas, Absorb and Mixing gates to:
- Recieve and return `[(Cell,F);25]` enforcing copy constraints between the steps to secure no witness manipulation happens due to prover altering the witnesses.
- Use `Layouter` to assign regions and avoid constantly tracking `region + offset`.
Fixes: #219

Iota, Absorb and Mixing gates Layouter + Cell copy strategy impl

---

bus-mapping/src/bytecode.rs
bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/evm/opcodes/dup.rs
bus-mapping/src/evm/opcodes/mload.rs
bus-mapping/src/evm/opcodes/mstore.rs
bus-mapping/src/evm/opcodes/pc.rs
bus-mapping/src/evm/opcodes/pop.rs
bus-mapping/src/evm/opcodes/push.rs
bus-mapping/src/evm/opcodes/sload.rs
bus-mapping/src/evm/opcodes/stackonlyop.rs
bus-mapping/src/evm/opcodes/swap.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/external_tracer.rs
bus-mapping/src/lib.rs
bus-mapping/src/mock.rs
bus-mapping/src/operation.rs
bus-mapping/src/operation/container.rs
bus-mapping/src/state_db.rs
geth-utils/lib/lib.go
integration-tests/tests/circuit_input_builder.rs
zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/state_circuit/state.rs

NOTE: this PR contains 2 commits. They can be reviewed independently.
- circuit_input_builder:
- Add `code_source` in Call to distinguish the executed contract
code from the contract address.
- In every `*CALL*/CREATE*`, properly set the `code_hash` on the
resutling `Call` object.  To do this we make use of the StateDB to
query the `code_hash` of an address at a given execution step.
- Require a partially-populated `StateDB` in the
`CircuitInputBuilder` to `handle_tx`.  The accounts that are
accessed in the block must be present in the `StateDB`.  Now the
`CircuitInputBuilder` constructor takes a `StateDB` and `CodeDB`.
- Move all methods of `CircuitInputStateRef` to the same impl block.
- state_db:
- Add `CodeDB` to store contract code indexed by code hash.
- mock:
- Introduce a helper …

bus-mapping: Handle code_hash in CircuitInputBuilder, Define more Operations

---

zkevm-circuits/src/evm_circuit/execution/jump.rs
zkevm-circuits/src/evm_circuit/execution/jumpi.rs
zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/execution/pc.rs
zkevm-circuits/src/evm_circuit/param.rs

This PR aims to fix the implementation of `JUMP` and `JUMPI` to support 8 bytes destination just like current `geth` implementation.
It previously assumes execution bytecode has maximum size <code>2<sup>24</sup>-1</code> and fit 3 bytes, because transaction size could only be up to 128kB. But the assumption would be broken if any change made to ethereum p2p protocol to allow a larger transaction size.
Also it simplify the check `is_zero` of condition to check the random linear combination directly instead of sum of bytes. (We already assume the random linear combination is collision resistent, so if random linear combination is zero, the decompose bytes should also sum to zero.)

Fix `JUMP` and `JUMPI` to support 8 bytes for destination

---

bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/evm.rs
bus-mapping/src/evm/opcodes/dup.rs
bus-mapping/src/evm/opcodes/jump.rs
bus-mapping/src/evm/opcodes/jumpi.rs
bus-mapping/src/evm/opcodes/mload.rs
bus-mapping/src/evm/opcodes/mstore.rs
bus-mapping/src/evm/opcodes/pc.rs
bus-mapping/src/evm/opcodes/pop.rs
bus-mapping/src/evm/opcodes/push.rs
bus-mapping/src/evm/opcodes/sload.rs
bus-mapping/src/evm/opcodes/stackonlyop.rs
bus-mapping/src/evm/opcodes/swap.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/operation.rs
bus-mapping/src/operation/container.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/state_circuit/state.rs

Rename TxAccessListStorageSlot to TxAccessListAccountStorage
Rename GlobalCounter to RWCounter and gc to rwc
Since StackOp and MemoryOp now have the `call_id` field, I've added the helper functions `push_memory_op` and `push_stack_op` so that the correct `call_id` is set automatically without requiring passing the value.
I've also modified the style of the Ord implementations for the Ops to a more clean and explicit way.

bus-mapping: Add call_id in StackOp and MemoryOp

---

bus-mapping/src/eth_types.rs
zkevm-circuits/src/evm_circuit/witness.rs

in a [previous commit](https://github.com/appliedzkp/zkevm-circuits/pull/240/files#diff-09bf944a4f9216c1053a271fea0ff2f7a985380789b990f8e4ac530159214df2R419-R421), in witness.rs, the tx steps for evm citcuit are incorrectly converted to empty vec, as a result, no steps are really tested.

fix tx_convert in witness

---

zkevm-circuits/src/evm_circuit.rs

We need use `table::FixedTableTag` to build circuits in external project, so I think we should make `table mod` public

public mod table

---

zkevm-circuits/src/state_circuit/state.rs

To build `StateCircuit` for external project. Same reason as https://github.com/appliedzkp/zkevm-circuits/pull/262

Public the StateCircuit fields 

---

.github/workflows/integration.yml
Cargo.lock
bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/eth_types.rs
bus-mapping/src/external_tracer.rs
bus-mapping/src/operation.rs
bus-mapping/src/rpc.rs
integration-tests/Cargo.toml
integration-tests/run.sh
integration-tests/tests/circuit_input_builder.rs
integration-tests/tests/circuits.rs
zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/state_circuit/state.rs

Add an integration tests for the evm and state circuits, using the input
generated by the circuit input builder and data queried from geth.
bus-mapping: Introduce `BuilderClient` which wraps a GethClient and
contains methods to generate the complete circuit inputs by doing all
the necessary steps: query geth, build partial state_db, etc.  Use this
`BuilderClient` in both the circuits and circuit_input_builder
integration tests.
---
For the state circuit I've used the `pub StateCircuit`.
For the evm circuit, I didn't find a pub circuit, so I copied the `TestCircuit` used in the evm circuit tests.  I don't know if this is the best approach, please let me know if you have a better idea!
I haven't included the state_circuit integration tests into the CI because, even though the evm_circuit is …

Add initial integration test with circuits

---

bus-mapping/src/eth_types.rs
bus-mapping/src/evm.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/table.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/math_gadget.rs
zkevm-circuits/src/evm_circuit/witness.rs

This PR aims to implement `ExecutionGadget` of `ExecutionState::BeginTx`.
The spec it follows could be found [here](https://github.com/han0110/zkevm-specs/blob/feature%2Fuse-legacy-tx-format/src/zkevm_specs/evm/execution/begin_tx.py).
Integration with `witness.rs` is left for further PRs, or left for `CALL` implementation PR

Implement `ExecutionState::BeginTx`

---

circuit-benchmarks/src/evm_circuit.rs
integration-tests/tests/circuits.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/jump.rs
zkevm-circuits/src/evm_circuit/execution/jumpi.rs
zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/execution/msize.rs
zkevm-circuits/src/evm_circuit/execution/pc.rs
zkevm-circuits/src/evm_circuit/execution/push.rs
zkevm-circuits/src/evm_circuit/execution/signextend.rs
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs

This PR aims to take down the random linear combination degree to 2, by introducing 31 constant instance columns with values <code>[r, r<sup>2</sup>, r<sup>3</sup>, ..., r<sup>31</sup>]</code>.

Use more instance columns for power of randomness

---

keccak256/src/arith_helpers.rs
keccak256/src/gates/gate_helpers.rs
keccak256/src/gates/rho_checks.rs
keccak256/src/gates/rho_helpers.rs
keccak256/src/gates/tables.rs
keccak256/src/gates/theta.rs

The current codebase uses many patterns that are difficult to reason and debug.
For example, 
```
b13_chunks.iter().fold(0, |acc, x| { acc * B9 + convert_b13_coef(*x)})
```
This requires `b13_chunks` to be in big endianness, but a reader might not be aware of it.
Solution: We collect them in the same function `f_from_radix_be` so that we have to reason only once. And from the function name, we know the input must be in big-endian.
We do a lot of manual base conversion like
```
for _ in 0..64 {
let remainder: u64 = mod_u64(&raw, B9);
acc += coef_transform(remainder) * base.clone();
raw /= from_base;
base *= to_base;
}
```
Solution: The `bigUint` has an expressive `to_radix_be` API to allow us to perform base conversion easily.

Handle base conversion nicer

---

keccak256/src/arith_helpers.rs
keccak256/src/gates/absorb.rs
keccak256/src/gates/base_conversion.rs
keccak256/src/gates/gate_helpers.rs
keccak256/src/gates/iota_b13.rs
keccak256/src/gates/iota_b9.rs
keccak256/src/gates/mixing.rs
keccak256/src/gates/rho.rs
keccak256/src/gates/rho_checks.rs
keccak256/src/gates/state_conversion.rs
keccak256/src/gates/tables.rs
keccak256/src/gates/theta.rs
keccak256/src/gates/xi.rs

`big_uint_to_field` and `biguint_to_f` are duplicated.
Keep `biguint_to_f` since it has 32 bytes check and `big_uint_to_field` uses the concrete type `Fp`.
Also removed unused `Lane<F>`

Remove biguint to field

---

bus-mapping/src/evm/memory.rs
bus-mapping/src/evm/opcodes/msize.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_pure_memory.rs
zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/execution/msize.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/step.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/memory_gadget.rs
zkevm-circuits/src/evm_circuit/witness.rs

Previous the `MSIZE` circuit pushes the memory size in words to the stack. However, the memory size that needs to be pushed to stack should be the memory size in bytes (see [here](https://github.com/ethereum/go-ethereum/blob/master/core/vm/instructions.go#L571) and [here](https://github.com/ethereum/go-ethereum/blob/master/core/vm/memory.go#L102)).
In addition, the memory size stored in the `StepState` is actually word size. So I change the field name from `memory_size` to `memory_word_size` to reduce the confusion in the future. This PR also adds the document to fields in the `StepState` and `ExecStep`.

Fix MSIZE opcode and add doc to step

---

keccak256/src/gates/rho_checks.rs
keccak256/src/gates/rho_helpers.rs

The current Rho witness uses an object that constantly mutates its state to compute the rotational base conversion, which is hard to reason and debug.
Create a new object that computes all the rotational base conversion in one shot. It can also print out the output of 64-bit output, which is helpful to check against the plain Keccak implementation.

Refactor rho witness

---

bus-mapping/src/evm.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_pure_memory.rs
zkevm-circuits/src/evm_circuit/execution/jump.rs
zkevm-circuits/src/evm_circuit/execution/jumpi.rs
zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/execution/msize.rs
zkevm-circuits/src/evm_circuit/execution/pc.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/step.rs
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/math_gadget.rs
zkevm-circuits/src/evm_circuit/util/memory_gadget.rs
zkevm-circuits/src/evm_circuit/witness.rs

This PR is part of #278, which extends memory gadgets to add/extend
- `MemoryAddressGadget` - To handle dynamic offset and length expansion. It's also useful for memory expansion opcode like `CALLDATACOPY`. 
- `MemoryExpansionGadget` - To support multiple expansion size. It's useful for `*CALL*` which assign 2 memory chunks as expansion targets.
It also refactors some frequently used constant and methods. For main changes, please refer to [`memory_gadget.rs`](https://github.com/appliedzkp/zkevm-circuits/pull/279/files#diff-19306e3baf34b1f4a23a09ee03e0f5bb5187d2e885af70cab30d81b4419c62a9)

Extend memory gadgets to handle dynamic offset and length

---

integration-tests/src/bin/gen_blockchain_data.rs
integration-tests/src/lib.rs
integration-tests/tests/circuit_input_builder.rs
integration-tests/tests/circuits.rs

In the integration testing setup we already had a block with an ETH transfer, but we just didn't use it as inputs for the state and evm circuit.
This is a very small PR that test (via integration) the state and evm circuit with an ETH transfer.  Currently the CircuitInputBuilder doesn't generate the BeginTx, EndTx, EndBlock circuit steps, so the circuits in this test will have mostly empty inputs; but this will soon change and I thought it was a good idea to already have an integration test for the moment we have those 3 steps generated by the CircuitInputBuilder.

Add integration test for ETH transfer

---

bus-mapping/src/error.rs
bus-mapping/src/lib.rs
eth-types/src/error.rs

Close https://github.com/appliedzkp/zkevm-circuits/issues/294
Move `bus-mapping` related errors out of `eth-types`.

Split eth-types Error

---

keccak256/src/gates/base_conversion.rs
keccak256/src/gates/tables.rs

#306
The input has 64 chunks. The lookup can process n chunks. We split the input chunks into 64/n groups and perform lookups and running sums for them.
The running sum is in big-endian style `accumulation = accumulation*radix**n + coef` to save columns.
This works fine when n is a multiple of 64, say 16.
But for base 9 we lookup n=5 chunks at a time. There would be one group that has 4 chunks.
Since we use big-endian style running sums, the 4 chunks group must be on the big-endian side. The current implementation put the 4 chunks group on the little-endian side.
Move the 4 chunks group to the big-endian side.

fix base conversion

---

keccak256/src/gates/gate_helpers.rs
keccak256/src/gates/rho.rs
keccak256/src/gates/rho_checks.rs
keccak256/src/gates/rho_helpers.rs
keccak256/src/gates/tables.rs

- Rho gate logic is complicated.
- We have 25 lane configs, each has 16~17 normal chunk configs and a special chunk config.
- Block count is a strange name
- The aggregation of Block count is complicated
- We do running sum for step2 and step3 accumulation "within" the lane config
- We do another running sum to sum up step2 and step3 accumulation "across" lanes  (BlockCountAccConfig)
- We then do the range check in the BlockCountFinalConfig.
- We clean up the lane config. A lane config now deals with normal chunks and special chunks together, no more sub-configs. Gate logic is more transparent now.
- Block count is renamed to overflow detector to reflect its true purpose.
- We collect all the overflow detector cells using copy gates. Use only a common running sum config to sum them within …

Simplify rho gates

---

bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/gas.rs
eth-types/src/evm_types/opcode_ids.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/gas.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/witness.rs

Implement the GasGadget for opcode GAS (5A). Specs at https://github.com/appliedzkp/zkevm-specs/pull/104.
Other changes:
1. Fix constant gas cost for OpcodeId::EXP

GasGadget for GAS opcode

---

Cargo.lock
zkevm-circuits/Cargo.toml
zkevm-circuits/src/bytecode_circuit.rs
zkevm-circuits/src/bytecode_circuit/bytecode_unroller.rs
zkevm-circuits/src/bytecode_circuit/param.rs
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/lib.rs

Spec: https://github.com/appliedzkp/zkevm-specs/pull/74
Disabled the `bytecode_invalid_index` for now because with the halo update it now gives an internal error on a circuit that should fail: `panicked at 'internal error: entered unreachable code', /home/brecht/.cargo/git/checkouts/halo2-b8251ca10f182e2b/b78c39c/src/dev/util.rs:48:42`. With the previous halo this test worked fine so not sure what's going on yet.
The constraint builder could be modified a bit more to make the circuit writing for these standalone circuits even a bit nicer, but Han's PR already does a couple of good changes so will await that one instead before doing so.

Bytecode unroller

---

Cargo.lock
Cargo.toml
bus-mapping/src/circuit_input_builder.rs
prover/Cargo.toml
prover/src/bin/gen_params.rs
prover/src/bin/prover_cmd.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/src/evm_circuit.rs

The first version includes two commands:
For generating circuit commitment parameters
that generates circuit proofs and prints them as json to stdout.
Another rpc daemon is needed for a later stage so that it becomes possible to defer generating/requesting proofs over http.

Feat/prover: add prover command line utilities

---

bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/caller.rs
bus-mapping/src/evm/opcodes/callvalue.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/caller.rs
zkevm-circuits/src/evm_circuit/execution/callvalue.rs
zkevm-circuits/src/evm_circuit/witness.rs

This PR depends on 
Based on https://github.com/appliedzkp/zkevm-specs/pull/90 and https://github.com/appliedzkp/zkevm-specs/pull/96
Take a special look at the approach I've followed to verify the equivalence between caller address in the StackOp (rlc encoded) and the CallContext (raw value) .

Implement circuit for CALLER and CALLVALUE opcode

---

bus-mapping/src/operation.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/table.rs
zkevm-circuits/src/evm_circuit/witness.rs

This PR is once #278, and aims to initialize last callee's information of `CallContext` in `BeginTx`.
For spec, see appliedzkp/zkevm-specs#99.
It depends on #292.

Initialize `LastCallee*` of `CallContext`

---

circuit-benchmarks/src/evm_circuit.rs

As @han0110 said. Before #341 &[&[]] is passed
(as single proof instance with no instnace columns values).
Now we were passing &[] only for instances.
Which basically means that num_proofs=0.
This was causing the errors during the benchmarks triggered in #352.
Resolves: #363 
Co-authored-by: @han0110

Fix EVM Circuit benchmark

---

.github/workflows/ci.yml
Makefile

Resolve https://github.com/appliedzkp/zkevm-circuits/issues/377
Resolve https://github.com/appliedzkp/zkevm-circuits/issues/378
With this change we just skip building the docs for our dependencies in the CI (which is not meaningful to us), and this should resolve the race that makes this test sometimes fail when building the `bitvec` docs for different versions in the same folder.

CI: Skip dependencies for doc checks

---

bus-mapping/src/circuit_input_builder.rs

There are two bugs when generating state access list from `GethExecTrace` by `gen_state_access_trace()`:
1. `CRAETE*` should push stack frame in a normal case.
2. `*CALL*` shouldn't push stack frame if there is no need. (e.g. CALL an EOA)
Now the program will panic and throw:
```
thread 'main' panicked at 'gen_inputs for BLOCK_NUM: InvalidGethExecStep("gen_state_access_trace: call stack will be empty", Step { pc: 0x0004, op: REVERT, gas: 170031, gas_cost: 0, depth: 2, error: None, stack: [0x0, 0x0], memory: [], storage: {} })', prover/src/bin/prover_cmd.rs:65:10
```
This PR aims to fix it.

fix "gen_state_access_trace" when handling the call stacks

---

bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/number.rs

As mentioned in #410, NUMBER opcode was missing in the opcodes.rs file
where all of the modules containing tests/opcode impls are listed.
This PR adds it and also updates the tests to the new `mock` API.
Resolves: #410

Add NUMBER module to opcodes and update testing infra

---

Cargo.lock
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/origin.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/origin.rs
zkevm-circuits/src/evm_circuit/witness.rs

Spec https://github.com/appliedzkp/zkevm-specs/pull/128
_Edit(1)_

ORIGIN opcode

---

CODEOWNERS

Since the solution https://github.com/appliedzkp/zkevm-circuits/pull/428 is impossible to implement as a bug affecting
the gh actions prevents it.
An alternative to automatically assign reviews for the reviewing team is
to use a CODEOWNERS file.
So this PR adds this file configured to assign all reviews to
`appliedzkp/zkevm-reviewers` and also Miha specifically to any state
circuit PR.
Resolves: https://github.com/appliedzkp/zkevm-circuits/issues/423

Add CODEOWNERS file to repo to auto-assign reviews

---

keccak256/src/permutation/base_conversion.rs
keccak256/src/permutation/circuit.rs
keccak256/src/permutation/mixing.rs
keccak256/src/permutation/rho.rs
keccak256/src/permutation/rho_checks.rs

By @therealyingtong's advice: We should create columns outside of the configurations instead of inside.
Before optimization:
```
Num advice columns: 102
Num fixed columns: 24
Num instance columns: 2
Num lookups: 6
Num gates: 19
Max advice rows 11087 - lane rotate conversion
num polys: 110
max_gate_degree_poly: 6 - 
```
After optimization:
```
Num advice columns: 31
Num fixed columns: 23
Num instance columns: 2
Num lookups: 6
Num gates: 18
Max advice rows 19042 - Constraint out_state and out_mixing
num polys: 109
max_gate_degree_poly: 6 - 
```
Most column creations happen in mixing (50 columns created) and base conversion (10 columns created). 
Comes with a cost of row increment. Since now rows are stacked together.
Related issue: #489

[Keccak] Optimization round: Reduce columns

---

Cargo.lock
circuit-benchmarks/Cargo.toml
eth-types/Cargo.toml
gadgets/Cargo.toml
integration-tests/Cargo.toml
keccak256/Cargo.toml
prover/Cargo.toml
zkevm-circuits/Cargo.toml

We bump the version for the relicensing purpose.
v2022_06_03 contains the new MIT+Apache2.0 licenses.

bump halo2_proofs version to v2022_06_03

---

zkevm-circuits/src/evm_circuit/execution/mul_div_mod.rs
zkevm-circuits/src/evm_circuit/util/math_gadget.rs

The words `a, b, c, d` are now passed as arguments in `construct` instead of being fetched via `query_word()`.
Closes #547

Refactor `MulAddWordsGadget`

---

keccak256/src/permutation/mixing.rs

`assign_out_mixing_states` already created the merged state. Returned it directly is the correct implementation.

small mixing fix

---

keccak256/src/permutation/circuit.rs
keccak256/src/permutation/rho.rs
keccak256/src/permutation/rho_checks.rs

In the current rho design, rho has 4 gates. 2 are used for the lookup, and 2 are for the running sum of input slices and output slices. Slices must be aligned in the same rows to make both the lookup and running sum work.
In this PR, we replace the 2 running sum gates with the generic gate. Generic gate copies cells and performs running sum for slices. This approach frees us 2 gates, 2 fixed columns, and 2 advice columns, but comes with the overhead of more rows.
This PR also unlocks #569, it was blocked that `q_special` is used in both running sum and lookup.

[Keccak] Replace running sum gates in rho with generic gate

---

zkevm-circuits/src/evm_circuit.rs

The type ExecutionConfig has been growing a lot with each opcode
gadget that we add.  Currently it's around 337 KiB.  By having functions
that return an EvmCircuit or a struct that contains an EvmCircuit,
we're actually allocating 337 KiB in the stack to hold the
ExecutionConfig.
So if we have a TestCircuit::configure that retruns a struct containing
EvmCircuit and calls EvmCircuit::configure that returns a struct
containing ExecutionConfig and calls ExecutionConfig::configure that
returns itself, by this point we have 3 times the size of
ExecutionConfig allocated in the stack, which means 1 MiB.
By moving this struct to the heap with Box as soon as possible, we will
only have one call in the entire call stack that requires allocating the
struct in the stack.
It may be interesting to look …

Box ExecutionConfig in EvmCircuit

---

circuit-benchmarks/src/state_circuit.rs
integration-tests/tests/circuits.rs
prover/src/compute_proof.rs
zkevm-circuits/src/evm_circuit/table.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/constraint_builder.rs
zkevm-circuits/src/state_circuit/test.rs
zkevm-circuits/src/test_util.rs

The number of rows in the state circuit needs to be constant so that the fixed columns that are used as selectors are fixed across all proofs so that the proving and verifying keys won't need to be to be regenerated for each block.

Pad StateCircuit to a fixed length

---

Cargo.lock
keccak256/Cargo.toml
keccak256/src/permutation/circuit.rs
keccak256/src/permutation/rho.rs
keccak256/src/permutation/rho_checks.rs
keccak256/src/permutation/tables.rs

These tables are using few rows:
- range 12
- range 169
- special chunks (13+1) *13/2 =91 rows
We can use tags to let them share table columns.
It can be unblocked by adding some generic gates.

[keccak] use tag to stack lookup table cells

---

prover/src/bin/prover_rpcd.rs

This avoids blocking rpc-server requests / rpc-server task interference.

prover/rpcd: use dedicated tokio runtime for proof computation

---

keccak256/src/permutation/circuit.rs
keccak256/src/permutation/mixing.rs
keccak256/src/permutation/tables.rs

We reuse the stackable table for the boolean flag lookup.
Cost: 1. Adds two rows to the stackable. 2. Need a tag advice cell when doing the lookup.
Benefit: don't need the [x(x-1), x+y=1] gate.
TODO: replace the whole mixing config with this.

add boolean flag lookup

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/circuit_input_builder/transaction.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/call.rs
bus-mapping/src/evm/opcodes/codesize.rs
bus-mapping/src/evm/opcodes/return.rs
bus-mapping/src/evm/opcodes/stop.rs
bus-mapping/src/operation.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/call.rs
zkevm-circuits/src/evm_circuit/execution/codecopy.rs
zkevm-circuits/src/evm_circuit/execution/copy_code_to_memory.rs
zkevm-circuits/src/evm_circuit/execution/copy_to_log.rs
zkevm-circuits/src/evm_circuit/execution/memory_copy.rs
zkevm-circuits/src/evm_circuit/execution/return.rs
zkevm-circuits/src/evm_circuit/execution/stop.rs
zkevm-circuits/src/evm_circuit/step.rs
zkevm-circuits/src/evm_circuit/table.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/witness.rs

This PR aims to implement `ExecutionState::STOP`. For spec, please refer to appliedzkp/zkevm-specs#100.
It also resolves #464 by removing the incomplete trace testing used in `COPYTOMEMORY` and `COPYCODETOMEMORY` because they should be covered by `CALLDATACOPY` and `CODECOPY`.
Currently some of tests using hand-crafted testing witness (instead of using `CircuitInputBuilder`) are failed by this PR, those unfixed include:

Implementation `ExecutionState::STOP`

---

zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs

the memory gadget was written long long ago. The "style" is a bit foreign compared to recent opcodes like CALLDATACOPY. Eg: MemoryGadget uses 32 identical (even rwc is same) rw lookup for mstore8, while in later opcodes we choose to use `cb.condition(cond, |cb| cb.lookup(...));`.  So i made a tiny change to make the style more consistent

refactor memory gadget

---

bus-mapping/src/evm/opcodes/call.rs
zkevm-circuits/src/evm_circuit/execution/call.rs

This PR fixes the inconsistency with spec in `CALL`.
Resolves #602.

Read caller's `CalleeAddress` instead of `CallerAddress` for new context's caller

---

zkevm-circuits/src/evm_circuit/execution/logs.rs

@lispc found when calculating next memory address,  it is wrong to use `mstart` directly as it is RLC value in  `MemoryAddressGadget`. good catch &  fix it in this PR !

fix memory offset rlc issue in log

---

bus-mapping/src/evm/opcodes/codecopy.rs
eth-types/src/bytecode.rs
eth-types/src/error.rs

vec\<u8\> should always be valid bytecode. So it will also be more consistent with BytecodeCircuit and geth

fix integration test 

---

zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/util.rs

This is a little utility (in the form of a test function) that prints to stdout a table with all the implemented states and their responsible opcodes with the following stats:
- height: number of rows used by the execution state
- gas: gas value used for the opcode execution
- height/gas: ratio between circuit cost and gas cost
The idea of this utility is to quickly check which are the worst case opcodes in terms of rows VS gas cost.
Here's the current table:
| state          | opcode         | h  |      g | h/g   |
| ---            | ---            | ---|    --- | ---   |
| STOP           | STOP           |  2 |      0 | inf |
| ADD_SUB        | ADD            |  5 |      3 | 1.667 |
| ADD_SUB        | SUB            |  5 |      3 | 1.667 |
| MUL_DIV_MOD    | MUL            |  8 |      5 …

Add test function with EVM circuit stats

---

bus-mapping/src/evm/opcodes/call.rs
zkevm-circuits/src/evm_circuit/execution/call.rs

Resovles #636.
It turns out to be a hidden implementation bug which can only be triggered by specific setting (account with code but with zero nonce), which should never happen after [EIP-161](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md)).

Fix `CALL` to calculate `is_empty_account` correctly

---

mock/src/test_ctx.rs

also fixes generating geth trace with zero transactions

mock/gen_geth_traces: explicitly require chain_id

---

bus-mapping/Cargo.toml
bus-mapping/src/evm.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/sha3.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit/execution/sha3.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/table.rs

Fixes the `integration-tests` warning after merging #635 for `SHA3` using a dummy gadget.
Still investigating failure because of Keccak lookup.

Fix RLC values in Copy/Keccak table lookup (SHA3)

---

bus-mapping/src/circuit_input_builder/execution.rs
bus-mapping/src/evm/opcodes/calldatacopy.rs
bus-mapping/src/evm/opcodes/codecopy.rs
bus-mapping/src/evm/opcodes/logs.rs
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit/execution/calldatacopy.rs
zkevm-circuits/src/evm_circuit/execution/codecopy.rs
zkevm-circuits/src/evm_circuit/execution/logs.rs
zkevm-circuits/src/evm_circuit/execution/sha3.rs
zkevm-circuits/src/evm_circuit/util/math_gadget.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/table.rs

They were being used to look up `copy_rwc_inc`, which can be directly computed.

Remove keys from CopyEvent

---

bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/balance.rs
bus-mapping/src/evm/opcodes/create.rs
bus-mapping/src/evm/opcodes/extcodecopy.rs
bus-mapping/src/evm/opcodes/extcodesize.rs

Apply "Hide writespace" can get a better diff view.
Currently statedb calculated incorrectly due to incomplete implementation of [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929). OpCode like `EXTCODESIZE` can easily break the system.
We need correct access list to calculate gas (like `CALL`, `CREATE`, `SSTORE`, etc.)
Some of the Opcode need further implementation of busmapping, `TODO` is added to comments.

reconstruct access list in bus-mapping

---

prover/src/bin/prover_rpcd.rs
prover/src/json_rpc.rs
prover/src/lib.rs
prover/src/server.rs
prover/src/shared_state.rs
prover/src/structs.rs
prover/tests/proverd.rs

This allows the `prover_rpcd` to scale horizontally by increasing the number of replicas with orchestrator tools
that support service discovery via DNS.
- each node/peer will try to obtain pending tasks
- simple algorithm to aid races to the same task
- redundant, because all tasks are replicated by each peer in case individual nodes are terminated

prover: add replica feature

---

.github/workflows/ci.yml
.github/workflows/select-runner.yml

Moves the selection and additional wakeup mechanism of the self-hosted runner into a reusable workflow.
It also removes the blocking behaviour for the whole ci workflow file of `consecutive-workflow-action` and replaces it with a github native concurrency group.

workflows: add reusable workflow for self-hosted runner

---

Cargo.lock
Cargo.toml
bus-mapping/Cargo.toml
circuit-benchmarks/Cargo.toml
eth-types/Cargo.toml
gadgets/Cargo.toml
integration-tests/Cargo.toml
zkevm-circuits/Cargo.toml
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/tx_circuit/sign_verify.rs

This enables us to use the Challenge API inside all the zkevm-circuits defined in this crate.
Resolves: #754

update: Port codebase to latest halo2/wrong versions

---

zkevm-circuits/src/bytecode_circuit/bytecode_unroller.rs
zkevm-circuits/src/bytecode_circuit/dev.rs

This helps in catching errors in circuit setup early. This change is important in tooling that does configure & synthesize the circuit to measure the circuit height but is not using the MockProver

bytecode circuit: throw synthesis error if witness is too large

---

zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/util.rs

As mentioned in #926, the `Challenges::mock` function was not adding different values for the `Challenges`. Therefore, a new function has been added that allows mocking by passing two different values (one per each challenge).
This allows to keep the API we previously had and also, reduce the need to send always 2 values when only 1 can be passed.
Resolves: #926
I considered to do a `Trait`-based approach by ussing `Add<Output=Self>` but `Expression<F>` does not implement this trait. Same happens for `Challenge` (the one in Halo2).
Therefore, the easiest way to not break the current API and also, not ask for 2 values when we don't need them to be different (everywhere minus Keccak) is to introduce a new function.

fix: Mock `Challenges` with different values

---

bus-mapping/src/circuit_input_builder/call.rs
bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes/callop.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs

Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/995
Spec PR https://github.com/privacy-scaling-explorations/zkevm-specs/pull/335
1.  Fix to not invoke `transfer` for call related opcodes (`CALLCODE`, `DELEGATECALL` and `STATICCALL`) expect `CALL`.
2. Fix to use `current_call.value` to setup next-call context for `DELEGATECALL`.
3. Add function `call_context_as_word` and fix `current_value` to `Word` type in circuit.
4. Integrate non-existing proof (`AccountFieldTag::NonExisting`) with `callee`.

Bug: fix to not invoke `transfer` for call related opcodes (except `CALL`)

---

zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/witness/block.rs

Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1013
As @lispc mentioned that `0x100` is a bad choice for randomness. It makes RLC and original value same...
We replaced it with `0x10000` and found a bug in `CallOpGadget`.
Solution:
After debugging, fixed `current_value` (only used for `DELEGATECALL`) from `Cell` type to `Word`. And makes test work.

Update `randomness` and fix `current_value` to `Word` type in `CallOpGadget`

---

bus-mapping/src/evm/opcodes/balance.rs
zkevm-circuits/src/evm_circuit/execution/balance.rs

Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1006
As @han0110 mentioned in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/973#discussion_r1056040648, we should replace checking account existing in state DB with account `is_empty` in `BALANCE` bus-mapping.
Also referenced [eip-158](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-158.md).

fix to check account empty for existence in `BALANCE` bus mapping

---

zkevm-circuits/src/evm_circuit/execution/mulmod.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/modulo.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/mul_add_words.rs

Fix issue #996 
Changes summary
`ModGadget` 
- exposing witness `k` so it's able to be unit-test. With k exposing, therefore also move witness generation logic outside.
- add test to cover soundness bug.
`MulModGadget`, op implementation
- rename `k` to `k2`,  plus adding `k1`, also passing `k1` for `ModGadget` to constrain.
`MulAddWordsGadget` 
- use `saturating_sub` to avoid underflow panic during carry calculation.
- add test to cover underflow

fix modulo soundness due to overflow

---

integration-tests/src/integration_test_circuits.rs
testool/src/statetest/executor.rs
zkevm-circuits/src/bytecode_circuit/bytecode_unroller.rs
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_constant.rs
zkevm-circuits/src/evm_circuit/execution/error_stack.rs
zkevm-circuits/src/evm_circuit/execution/gas.rs
zkevm-circuits/src/exp_circuit.rs
zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs
zkevm-circuits/src/pi_circuit.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/tx_circuit.rs
zkevm-circuits/src/tx_circuit/sign_verify.rs
zkevm-circuits/src/util.rs
zkevm-circuits/src/witness/block.rs

Add two new unit tests for the super circuit:
- block with 1 tx with max_txs=2
- block with 2 txs with max_txs=2 The super circuit unit tests are still marked as ignored so that they are skipped in the github PR checks because they take a long time to run
Improve ergonomics of rows estimation per circuit.  Add a function `min_num_rows_block` to each circuit to get the minimum number of required rows to prove a given block. Related to https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/982
Resolve https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/883

Improve supercircuit usage

---

zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/test_util.rs

in evm circuit, if padding is enabled, then a lot of EndBlock will be assigned with the expensive `CachedRegion` way.
In this PR, these same non-last EndBlock steps are only handled by CachedRegion once, and then are repeated until the last EndBlock. 
For a 1<<18 circuit, assignment time reduced from 28s to 4s in my laptop

opt(assignment): speedup EndBlock padding

---

mock/src/lib.rs
zkevm-circuits/src/evm_circuit/execution/extcodesize.rs

Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1037
Add `code_size_bytes` of cell array to fix inconsistency issue. Reference [similar code of CODESIZE](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/codesize.rs#L24).

Bug: fix inconsistency `EXTCODESIZE`

---

bus-mapping/src/evm/opcodes/balance.rs
bus-mapping/src/evm/opcodes/extcodehash.rs
bus-mapping/src/evm/opcodes/extcodesize.rs
zkevm-circuits/src/evm_circuit/execution/balance.rs
zkevm-circuits/src/evm_circuit/execution/extcodehash.rs
zkevm-circuits/src/evm_circuit/execution/extcodesize.rs

Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1041
Fixed to not split `Address` (calling `to_address` function) when stack ~~push or~~ pop in both bus-mapping and assign exec step of circuit. The first 12-bytes may be lost.
Referenced [code_address](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/callop.rs#L42) in `CallOpGadget`.

fix stack value `address` to `Word` type in gadgets

---

zkevm-circuits/src/evm_circuit/util/math_gadget/abs_word.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/test_util.rs

Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1021
Add a comment for `AbsWord` special case, and corresponding test cases.
Referenced [I256::MAX](https://docs.rs/ethers-core/latest/src/ethers_core/types/i256.rs.html#105) and [I256::MIN](https://docs.rs/ethers-core/latest/src/ethers_core/types/i256.rs.html#108) of [ethers_core](https://docs.rs/ethers-core/latest/ethers_core/) for test constant `WORD_SIGNED_MAX` and `WORD_SIGNED_MIN`.

fix: add comment for special case of `x = -2^255` to `AbsWord` gadget

---

bus-mapping/src/evm/opcodes/balance.rs
bus-mapping/src/evm/opcodes/callop.rs
bus-mapping/src/evm/opcodes/extcodecopy.rs
bus-mapping/src/evm/opcodes/extcodehash.rs
bus-mapping/src/evm/opcodes/extcodesize.rs
gadgets/src/batched_is_zero.rs
gadgets/src/lib.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution/balance.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/codecopy.rs
zkevm-circuits/src/evm_circuit/execution/codesize.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution/extcodehash.rs
zkevm-circuits/src/evm_circuit/execution/extcodesize.rs
zkevm-circuits/src/evm_circuit/execution/stop.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/math_gadget.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/constraint_builder.rs
zkevm-circuits/src/state_circuit/test.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/witness/mpt.rs

Add BatchedIsZeroChip in gadgets
Update the following opcode gadgets to handle non-existing accounts via code_hash == 0:
- BALANCE
- EXTCODEHASH
- EXTCODESIZE
- callop (CALLCODE, DELEGATECALL, STATICCALL, CALL)
Missing:
- EXTCODECOPY (the circuit is currently not implemented, I'll update it once https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/720 is merged)
Important note: By handling the non-existence proofs from the state circuit (which requires detecting the special case of storage 0->0 or account,code_hash 0->0 to swap the proof type to non existence in the MPT lookup), the state circuit degree has increased from 9 to 12.  I could keep it at 9 by introducing an intermediate column and splitting the degree >9 expression.  Is it a problem to keep the degree at 12? …

feat(state): constrain non-exist proof for account and storage

---

bus-mapping/src/evm/opcodes/extcodecopy.rs
zkevm-circuits/src/evm_circuit/execution/extcodecopy.rs

1.  use non-exist-proof
2. use challenge api
3. fix stack push order
4. add EXTERNAL_ADDRESS to TestContext
5. fix reversible_write_counter
previously, due to the incorrect param stack pushing order, an OOG error is triggered and handled by DummyGadget, so all the above errors cannot be catched by tests.

fix extcodecopy: non-exsit-proof, challenge api, and other fixes

---

zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/test.rs
zkevm-circuits/src/table.rs
zkevm-circuits/src/witness/mpt.rs

and other improvements:
1. rename power_of_randomness to instance in state circuit tests. There is no power_of_randomness now.
2. change MptUpdates from HashMap to BTreeMap. So each run of tests produces same columns without non-deterministic. Useful for debugging.

state circuit allows non zero old_state_root

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_constant.rs
zkevm-circuits/src/evm_circuit/execution/error_stack.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs

try to resolve issue https://github.com/privacy-scaling-explorations/zkevm-specs/issues/346

 constrain rw_counter_end_of_reversion for failed step

---

bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/circuit_input_builder/execution.rs
circuit-benchmarks/src/super_circuit.rs
integration-tests/src/integration_test_circuits.rs
integration-tests/tests/circuit_input_builder.rs
testool/src/statetest/executor.rs
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/witness/block.rs

Fix sub-circuit padding & Pk/Vk non-determinisim to prevent variadic circuit sizes

---

Cargo.lock
Cargo.toml
bus-mapping/Cargo.toml
circuit-benchmarks/Cargo.toml
eth-types/Cargo.toml
gadgets/Cargo.toml
integration-tests/Cargo.toml
testool/Cargo.toml
zkevm-circuits/Cargo.toml

Updates:
- halo2_proofs to `v2023_01_20`
- halo2wrong to `v2023_01_20`
Resolves: #1085

chore: Update halo2_proofs & halo2wrong to latest releases

---

zkevm-circuits/src/table.rs

With the new halo2_proofs release added in #1094, we no longer need to have an empty row for the mpt table so that the error reporting functions don't panic on finding a Region with no rows.
Resolves: #1032

fix: Revert empty row inclusion in MPT table

---

circuit-benchmarks/src/copy_circuit.rs
zkevm-circuits/src/copy_circuit.rs

- Refactor copy circuit to take vec of `CopyEvent`, rather than a `Block`
- Restores negative tests for copy circuit

refactor copy circuit

---

zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/super_circuit.rs

Avoid conditional assignation of external tables in CopyCircuit Circuit impl.  Tests for the CopyCircuit outside of the zkevm-crates require the assignation to external tables, which was not happening due to a recent refactor of the CopyCircuit.
Resolve https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1102

Fix: CopyCircuit integration tests

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/callop.rs
bus-mapping/src/evm/opcodes/error_oog_call.rs
bus-mapping/src/operation.rs
bus-mapping/src/state_db.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution/error_stack.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/witness/block.rs
zkevm-circuits/src/witness/rw.rs

After this was merged https://github.com/privacy-scaling-explorations/zkevm-specs/pull/354 the rule for opcodes that can access non-existing accounts is to first read the CodeHash, and only if it's not 0 (meaning that the account exists), proceed with other account field reads.  If a field read is performed to a non-existing account, this may end up mapping to an MPT account field proof for a non-existing account (which are not supported); so the MPT proof would be impossible to generate.  We can add some checks to make sure we don't implement any circuit that generates this situation; but we can even add more sanity checks to detect possible bugs early.  In particular we can check for each account field lookup (either read or write): 
- That a READ doesn't change the field value
- That …

feat: panic on invalid account lookups

---

circuit-benchmarks/src/super_circuit.rs
integration-tests/src/integration_test_circuits.rs
integration-tests/tests/circuits.rs
testool/src/statetest/executor.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/tx_circuit.rs

- unify circuit proving test in integration tests with a single generic function that takes a SubCircuit
- fix: Invalid `SubCircuit.instance()` implementation for TxCircuit
- allow setting the mock_randomness for the SuperCircuit externally
Resolve https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1099
Resolve https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1081
Related to (hopefully this PR resolves some of these issues):
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1050
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1051
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1052
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1053
- …

chore: unify circuits in integration tests

---

Cargo.lock
bus-mapping/src/circuit_input_builder/input_state_ref.rs
gadgets/src/evm_word.rs
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/exp_circuit.rs
zkevm-circuits/src/table.rs

This includes:
1) Annotations for all EVM Circuit columns (a bit challenging to make them really useful considering the `CellManager` basically prevents us to annotate properly as we have a single `Region`.
2) Includes a rework on the `LookupTable` trait which allows to automatically annotate the lookup tables included in a circuit with a single call (this happens in the EVM Circuit in this PR for example).
This addresses `EVMCircuit` in https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1106

Annotate LookupTable & EVM Circuit columns

---

bus-mapping/src/error.rs
bus-mapping/src/evm/opcodes/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/step.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/witness/step.rs

Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1139
Spec PR https://github.com/privacy-scaling-explorations/zkevm-specs/pull/368 has been merged.
1. Merge enum value `OogError::CallCode`, `DelegateCall` and `StaticCall` into `OogError::Call`.
2. Merge enum value `ExecutionState::ErrorOutOfGasCALLCODE`, `ErrorOutOfGasDELEGATECALL` and `ErrorOutOfGasSTATICCALL` into `ExecutionState::ErrorOutOfGasCALL`.
3. Update bus-mapping and zkevm-circuit `error_oog_call` to handle CALLCODE, DELEGATECALL and STATICCALL opcodes.
4. Update both root and internal test cases in circuit.

feat: add OOG error handling for `CALLCODE`, `DELEGATECALL` and `STATICCALL` to `ErrorOOGCall`

---

Cargo.lock
zkevm-circuits/Cargo.toml
zkevm-circuits/src/lib.rs
zkevm-circuits/src/root_circuit.rs
zkevm-circuits/src/root_circuit/aggregation.rs
zkevm-circuits/src/super_circuit.rs

This PR aims to implement `RootCircuit` for `SuperCircuit` aggregation, to replace current one in `zkevm-chain` repo.
It uses the latest `snark-verifier` (previously `plonk-verifier`) so it requires to upgrade the `halo2` and `halo2wrong` tag, tho it doesn't require any change (it's just that we could use stable channel rust now but `zkevm-circuits` itself still requires nightly).
Resolves https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/664.

Implement `RootCircuit` for `SuperCircuit` aggregation

---

circuit-benchmarks/src/bytecode_circuit.rs
circuit-benchmarks/src/copy_circuit.rs
circuit-benchmarks/src/evm_circuit.rs
circuit-benchmarks/src/exp_circuit.rs
circuit-benchmarks/src/packed_multi_keccak.rs
circuit-benchmarks/src/pi_circuit.rs
circuit-benchmarks/src/state_circuit.rs
circuit-benchmarks/src/super_circuit.rs
circuit-benchmarks/src/tx_circuit.rs

Log messages across different prover benchmark tests differ slightly. This PR makes them uniform to make it easier to
parse and report results
```
circuit-benchmarks/src/bytecode_circuit.rs
circuit-benchmarks/src/copy_circuit.rs
circuit-benchmarks/src/evm_circuit.rs
circuit-benchmarks/src/packed_multi_keccak.rs
circuit-benchmarks/src/pi_circuit.rs
circuit-benchmarks/src/super_circuit.rs
circuit-benchmarks/src/copy_circuit.rs
circuit-benchmarks/src/exp_circuit.rs
circuit-benchmarks/src/tx_circuit.rs
```

uniform log messages for benchmark proof generation/verification

---

zkevm-circuits/src/evm_circuit/execution.rs

Annotate execution circuit q_step column
Part of https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1106
- Annotate execution circuit q_step column
Following example linked in issue.
Compilation didn't fail.

Annotate execution circuit q_step column

---

gadgets/src/mul_add.rs
zkevm-circuits/src/exp_circuit.rs

Adds columns annotations to Exp circuit.
Part of https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1106
- Adds columns annotations to Exp circuit.
Following example linked in issue.
Compilation didn't yield errors.
Not sure if calling `exp_table.annotate_columns(meta);` as has been done in execution gadget, I guess it can be done twice without problem.

Exp circuit annotations

---

.github/workflows/ci.yml
.github/workflows/lints.yml

Make some modifications to the required workflow files in an attempt to fix the merge queue not triggering workflows.
- [_item_]
<hr>
```
```
- What types of design choices …

merge queue fixes

---

eth-types/src/geth_types.rs
eth-types/src/lib.rs

[_PR description_]
From Transaction to TransactionReq panic if transaction's to is none, found a solution from scroll's repo https://github.com/scroll-tech/zkevm-circuits/blob/82c44f0ac8e1dc9dd88fb1d8e8edbd88476816af/eth-types/src/geth_types.rs#L190
- [_item_]
make a simple unit test

fix none tx.to issue

---

zkevm-circuits/src/evm_circuit/util/math_gadget/rlp.rs

The `CREATE2` input length and `RLC(input)` were not tested during the #1164 merge. This PR adds and enables a test for CREATE2 specific `input_len` and `input_rlc` calculation.
The helper container can test both `CREATE` and `CREATE2` inputs (length and `RLC(input_bytes)`). These inputs are then used as inputs to do a lookup to the Keccak table.
- #1164 
- #1140 (needs rebasing after this is merged)

[Tests] CREATE2 inputs in Math Utils Gadget

---

Makefile
bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/balance.rs
bus-mapping/src/evm/opcodes/callop.rs
bus-mapping/src/evm/opcodes/error_oog_call.rs
bus-mapping/src/evm/opcodes/extcodecopy.rs
bus-mapping/src/evm/opcodes/extcodehash.rs
bus-mapping/src/evm/opcodes/extcodesize.rs
bus-mapping/src/evm/opcodes/selfbalance.rs
bus-mapping/src/mock.rs
integration-tests/tests/circuit_input_builder.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/lib.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/stats.rs

feat: Add copy circuit stats by exec state like the ones we had for evm circuit and state circuit.
refactor: move duplicate code used to get circuit stats by exec state into a new module, which also contains a helper struct to draw formatted tables
feat: add the `warn-unimplemented` fature in `zkevm-circuits` so that it can be enabled/disabled when using the zkevm-circuits crate.
Here are the stats for the Copy Circuit
| state          | opcode         | h    | g     | h/g    |
| -------------- | -------------- | ---- | ----- | ------ |
| CALLDATACOPY   | CALLDATACOPY   | 8192 | 803   | 10.202 |
| CODECOPY       | CODECOPY       | 8192 | 803   | 10.202 |
| EXTCODECOPY    | EXTCODECOPY    | 8192 | 900   | 9.102  |
| RETURNDATACOPY | RETURNDATACOPY | 8192 | 803   | 10.202 |
| LOG …

feat: Add copy circuit stats by exec state

---

Cargo.toml
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/test_util.rs

This is an experiment to cache the EVM Circuit configuration so that it's reused in all unit tests, to see if github workflow tests time is reduced.

feat: cache EVM circuit configuration in unit tests

---

bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/error_oog_exp.rs
eth-types/src/evm_types.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_exp.rs
zkevm-circuits/src/evm_circuit/execution/exp.rs

Add `ErrorOOGExpGadget` to handle OOG error of `EXP` opcode.
Gas calculation could reference [this go-ethereum function](https://github.com/ethereum/go-ethereum/blob/master/core/vm/gas_table.go#L351).
Spec Markdown PR https://github.com/privacy-scaling-explorations/zkevm-specs/pull/388
Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1231
Tested with unit-test cases.

Implement circuit for `EXP` OOG error

---

zkevm-circuits/src/evm_circuit.rs

This is a very small PR adding documentation to the EvmCircuitCached introduced in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1234 which I forgot to add previously.  There's no change in the code.

docs: add documentation on evm_circuit::cached

---

zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/witness/block.rs
zkevm-circuits/src/witness/rw.rs

1. in evm circuit, check_rw_lookup only checks rw inside step instead of whole block. Improve running speedup greatly.
2. add a `check_value` method for RwMap. Without running StateCircuit we can quickly find almost problems related to rw::value.
- [_item_]
<hr>
```
- Changed xxxx …
```

improve debuggability: better check of rw lookup and rw value

---

zkevm-circuits/src/evm_circuit/execution/error_oog_exp.rs

Update `ErrorOOGExpGadget` according to `CommonErrorGadget` refactor in PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1177.
Could be tested via ErrorOOGExpGadget unit-test cases.

fix: update `ErrorOOGExpGadget` to use `CommonErrorGadget`

---

zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs

With `KECCAK_DEGREE=19`, `get_num_bits_per_absorb_lookup()` is 11. In some places, `2**3**11` overflows `u32`.
Replace with `u64`. Also use faster bitshifts like Axiom’s version.
Port fix from Scroll https://github.com/scroll-tech/zkevm-circuits/pull/335
- Compute in `u64`
cargo test -p zkevm-circuits --features test --release -- keccak

fix/keccak-decode-overflow: calculate with bitshifts in u64

---

bus-mapping/src/evm/opcodes/extcodecopy.rs
zkevm-circuits/src/evm_circuit/execution/extcodecopy.rs

Fix to add stack-read operation of whole `external_address` word to RW table in bus-mapping, and lookup that word in circuit.
Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1252
Could be tested via test cases of `ExtcodecopyGadget`.

Bug: fix to not truncate `external_address` for `EXTCODECOPY`

---

zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs
zkevm-circuits/src/state_circuit.rs

- Improves the keccak performance for padding rows significantly
- small performance gain in state circuit with high padding rows

Perf improvements for keccak,state circuit

---

bus-mapping/src/evm/opcodes/error_invalid_jump.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs

Reference go-ethereum function [opJump](https://github.com/ethereum/go-ethereum/blob/master/core/vm/instructions.go#L538
) and [validJumpdest](https://github.com/ethereum/go-ethereum/blob/master/core/vm/contract.go#L86), try to handle `destination` overflow in `ErrorInvalidJumpGadget`.
Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1257
Add a new test case `invalid_jump_dest_overflow`.

Bug: fix to handle `destination` overflow in `ErrorInvalidJumpGadget`

---

zkevm-circuits/src/evm_circuit/execution.rs

This improves compilation times. 
No issue, quality-of-life PR.
- [ x ] Bug fix (non-breaking change which fixes an issue)
The function `configure_gadget` is split into a generic and a non-generic functions.
Generics are not free. They are the biggest contributor to compile times and to CPU code cache. `configure_gadget` is the largest example of this phenomenon.
I measured about 2x fewer LLVM IR with `cargo llvm-lines`. Even 3x in Scroll’s fork. The improvement in clock time depends a lot on exactly what you do, but it will be faster.
cargo test --features test -p zkevm-circuits --release

Compile time of configure gadget

---

zkevm-circuits/src/keccak_circuit/table.rs
zkevm-circuits/src/keccak_circuit/util.rs

This PR verifies the properties of the lookup tables used in Keccak.
A port of https://github.com/scroll-tech/zkevm-circuits/pull/326
This is a good regression test before https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1241
- A test circuit that populates the fixed lookup tables using the functions under test.
- Check that the table contain valid values, and nothing else.
- Minor refactoring for testability. Make pure functions that calculate parameters, and isolate the dependency on environment variables.
cargo test -p zkevm-circuits --features test --release -- keccak

test-keccak-normalize-table: unit tests for the content of lookup tables

---

bus-mapping/src/evm/opcodes.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs

Fixes state.tx_accesslist_account_write for warm addresses.
Fixes: https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1233
`cargo test -p zkevm-circuits --features test prover_error -- --nocapture --ignored`
with zkevm-chain fixtures

fix tx_accesslist_account_write for warm addresses in BeginTx

---

Cargo.lock
mock/src/test_ctx.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/tests/prover_error.rs

Introduces a new `prover_error` test that allows testing the SuperCircuit with the generated fixtures from zkevm-chain errors.
Instructions:
Copy the `errors/<block number>` directory into the zkevm-circuits git root as `block` and run via `cargo test -p zkevm-circuits --features test prover_error -- --nocapture --ignored`. Change any constant variables like `MAX_TXS` to suit your needs.

zkevm_circuits: add zkevm chain fixture test

---

zkevm-circuits/src/pi_circuit.rs

This implements the `SubCircuit` trait for `PiTestCircuit`. PiTestCircuit isn't a subcircuit in technical terms and hence panics when `synthesize_sub` is called with a message to use the `PiCircuit` for embedding instead.
After moving some code of macro bodies I had to update the types and zkevm-chain now requires the `SubCircuit` trait being implemented for all circuits used. Technically, PiTestCircuit isn't a Subcircuit. But without creating a new trait it makes downstream usage more streamlined.
In zkevm-chain

subcircuit trait for PiTestCircuit

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes/return_revert.rs
zkevm-circuits/src/evm_circuit/execution/return_revert.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs

Align specs in EIP-211: returndatasize should be 0 after create/create2 success call
Closed https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1250
- revamp `handle_restore_context` and `handle_return` to be able to handle create/create2 returndatasize 0 case
- add unittest to assure 1. create/create2 contract created successfully 2. bytecode with returndatasize/returndatacopy satisfy constraints
- add few comments for existing hardcode magic number
use magic number to access rws indices during assignment is inevitable. We might need a better design to address this issue.
One possible way is refactor, by bumping and returning index when every time calling rw_lookup, and exposing index value into XXXXXGadget like other `Cell` fields
`cargo test --package zkevm-circuits …

follow EIP-211: create/create2 successful case must set empty returndatasize

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs

Fixes the following error that can not be silenced from zkevm-chain
```
Checking bus-mapping v0.1.0 (/app/deps/zkevm-circuits/bus-mapping)
error[E0658]: `let` expressions in this position are unstable
--> deps/zkevm-circuits/bus-mapping/src/circuit_input_builder/input_state_ref.rs:976:12
|
976 |         if let Ok(caller_ctx) = self.caller_ctx_mut() && (
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
= help: add `#![feature(let_chains)]` to the crate attributes to enable
For more information about this error, try `rustc --explain E0658`.
error: could not compile `bus-mapping` due to previous error
```

bus-mapping: fix clippy errors

---

zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/constraint_builder.rs
zkevm-circuits/src/table.rs
zkevm-circuits/src/witness/mpt.rs

I synchronized memory and mpt proof according to spec synchronization.
https://github.com/privacy-scaling-explorations/zkevm-specs/pull/385
I did following things.
- add [2.1 constraint](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/state-proof.md#memory)
- update ProofType
I would appreciate it if you could confirm.
Thank you!

memory and mpt proof synchronization

---

zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs

Found by `testool` cases (`ABAcalls1_d0_g0_v0`).
Reference [go-ethereum callGas function](https://github.com/ethereum/go-ethereum/blob/master/core/vm/gas.go#L44), the returned gas (if input is Unit64 overflow) could also cause out of gas error.
Add unit-test case `test_oog_call_with_overflow_gas` (failed without this fix).

Fix to enable `gas_is_u64` for failed Calls

---

.github/workflows/integration.yml
integration-tests/README.md
integration-tests/run.sh

This PR introduces github-ops functionality to zkevm-circuits/integration-tests, allowing execution on ephemeral AWS hosted runners. Execution mode is parameterized based on event trigger type and prover type selection.    
- .github/workflows/integration.yml
- integration-tests/run.sh
- integration-tests/README.md
```
- A new job that initializes prover and instance type workflow variables 
- run.sh updated to Compose V2
- Updated README.md file to reflect the updated docker compose commands
```
As per new integration tests execution mode, we run the tests manually, on schedule or on specific GitHub events (PR, push to main). Depending on workflow setup, test is executed either with real or mock prover, thus different AWS instance is selected to accommodate increased …

Integration tests with ephemeral runners via GitHub ops

---

bus-mapping/src/evm/opcodes/error_return_data_outofbound.rs
zkevm-circuits/src/evm_circuit/execution/error_return_data_oo_bound.rs

Fix overflow cases of `ErrorReturnDataOutOfBound` state. Found by `testool` cases (`bufferSrcOffset_d108(fail)_g0_v0`).
Refactor unit-test cases of `ErrorReturnDataOutOfBound` to 4 categories:
- data_offset > u64::MAX
- data_offset + size > U256::MAX
- data_offset + size (mod U256) > u64::MAX
- data_offset + size > return_data_length

Fix overflow cases of `ErrorReturnDataOutOfBound`

---

zkevm-circuits/src/evm_circuit/execution/returndatacopy.rs

error_return_data_oo_bound has covered the negative test. We don't need to redo it in returndatacopy
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1189
- Refactor
- Remove comments
Run unit tests in error_return_data_oo_bound
Notes (TODO?)
- We should refactor the unit tests in error_return_data_oo_bound, returndatacopy and other files as they use similar test codes to construct contract for testing.

Remove comments as negative test is covered by error_return_data_oo_bound

---

Makefile
zkevm-circuits/src/stats.rs

Descending the order of h/g tells us what operations should be optimized first.
slightly related to #1328
Before 
```
| state          | opcode         | h    | g     | h/g    |
| -------------- | -------------- | ---- | ----- | ------ |
| STOP           | STOP           | 13   | 0     | inf    |
| ADD_SUB        | ADD            | 3    | 3     | 1.000  |
| ADD_SUB        | SUB            | 3    | 3     | 1.000  |
| MUL_DIV_MOD    | MUL            | 3    | 5     | 0.600  |
| MUL_DIV_MOD    | DIV            | 3    | 5     | 0.600  |
| MUL_DIV_MOD    | MOD            | 3    | 5     | 0.600  |
| SDIV_SMOD      | SDIV           | 3    | 5     | 0.600  |
| SDIV_SMOD      | SMOD           | 3    | 5     | 0.600  |
| SHL_SHR        | SHL            | 3    | 3     | 1.000  |
| SHL_SHR        | …
```

Sort state circuit stats by descending order of h/g

---

.github/workflows/test-features.yml

Add a single dummy step that can be easily added to the branch protection rules.
Without this change any matrix combination has to be added to branch protection rules independently.

ci/test-features: add dummy complete step for branch rules

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/callop.rs
bus-mapping/src/evm/opcodes/create.rs
bus-mapping/src/evm/opcodes/error_invalid_jump.rs
bus-mapping/src/evm/opcodes/error_oog_call.rs
bus-mapping/src/evm/opcodes/error_oog_exp.rs
bus-mapping/src/evm/opcodes/error_oog_log.rs
bus-mapping/src/evm/opcodes/error_oog_sload_sstore.rs
bus-mapping/src/evm/opcodes/error_return_data_outofbound.rs
bus-mapping/src/evm/opcodes/error_simple.rs
bus-mapping/src/evm/opcodes/error_write_protection.rs
bus-mapping/src/evm/opcodes/return_revert.rs
bus-mapping/src/evm/opcodes/stop.rs

- unify handle_restore_context and gen_restore_context_ops
fix #1186 
- merge `gen_restore_context_ops` into `handle_restore_context`

feat/#1186 Unify restore_ctx and handle_return in bus_mapping

---

bus-mapping/src/circuit_input_builder/tracer_tests.rs
bus-mapping/src/evm/opcodes/balance.rs
bus-mapping/src/evm/opcodes/calldatacopy.rs
bus-mapping/src/evm/opcodes/logs.rs
bus-mapping/src/evm/opcodes/sha3.rs
eth-types/src/bytecode.rs
eth-types/src/evm_types/memory.rs
mock/src/lib.rs
zkevm-circuits/src/evm_circuit/execution/balance.rs
zkevm-circuits/src/evm_circuit/execution/calldatacopy.rs
zkevm-circuits/src/evm_circuit/execution/dup.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution/error_return_data_oo_bound.rs
zkevm-circuits/src/evm_circuit/execution/error_stack.rs
zkevm-circuits/src/evm_circuit/execution/logs.rs
zkevm-circuits/src/evm_circuit/execution/push.rs
zkevm-circuits/src/evm_circuit/execution/return_revert.rs
zkevm-circuits/src/evm_circuit/execution/returndatacopy.rs
zkevm-circuits/src/evm_circuit/execution/returndatasize.rs
zkevm-circuits/src/evm_circuit/execution/signed_comparator.rs
zkevm-circuits/src/evm_circuit/execution/swap.rs
zkevm-circuits/src/exp_circuit/test.rs
zkevm-circuits/src/stats.rs

Refactor and add more helper functions to Bytecode:
- Removed several functions such as `call`, `balance`, `mstore`, `calldatacopy`, and `return_bytecode`
- Added `op_jumpdest` function
- Implemented `impl_push_n` macro to generate functions for `op_push1` to `op_push32`
- Implemented `impl_other_opcodes` macro to generate functions for various opcodes like `op_stop`, `op_add`, `op_mul`, `op_sub`, and so on
- Renamed opcode helper functions to `op_{opcode}` for consistency and clarity
N/A
- Removal of several functions
- Addition of `op_jumpdest` function
- Implementation of `impl_push_n` macro to generate functions for `op_push1` to `op_push32`
- Implementation of `impl_other_opcodes` macro to generate functions for various opcodes
- Renaming of opcode helper functions
This refactor …

[refactor] refactor and add more helper in Bytecode

---

Cargo.lock
zkevm-circuits/Cargo.toml
zkevm-circuits/src/bytecode_circuit/bytecode_chiquito.rs
zkevm-circuits/src/bytecode_circuit/test.rs

- Use Chiquito tag version "v2023_04_24", which updated PLONKish lookup table syntax with auto annotation features
- Updated the bytecode circuit according to the new syntax
This is an update to Leo's original pull request here: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1348

Updated Chiquito lookup table grammar for bytecode circuit

---

gadgets/src/mul_add.rs

An important typo.
- Add term `a[3] * b[1]` (was written as `b[2]`).

zellic-fix-1: fix typo in multiplied terms

---

gadgets/src/is_zero.rs
zkevm-circuits/src/bytecode_circuit/circuit.rs

We simplify the assignment logic in the bytecode circuit by reducing the number of function arguments. The reduction is achieved by
1. Construct IsZero Chips early and make them a part of the circuit struct so that they don't stay with the function arguments.
2. Create a new row struct that carries all the relevant data.
This would be part of #1391. 
- I avoid using `BytecodeRow` in the `bytecode_unroller` since they are part of the future simplification plan.
Sent to the CI and pray.

Simplify bytecode circuit assignment

---

bus-mapping/src/operation.rs

Fix an infinite loop from a `From` implementation calling itself.
Resolve https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1420
Related https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1417
@ChihChengLiang found that this issue was introduced in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1406 and by debugging on the debug build I found the infinite loop (which caused the stack to overflow which terminated the program with a segfault).  The segfault is not observed in the release build, I guess the compiler optimizes the recursive call into an infinite loop, so the stack is never exhausted.

Fix infinite loop

---

bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/evm/opcodes/calldatacopy.rs
bus-mapping/src/evm/opcodes/callop.rs
bus-mapping/src/evm/opcodes/codecopy.rs
bus-mapping/src/evm/opcodes/create.rs
bus-mapping/src/evm/opcodes/extcodecopy.rs
bus-mapping/src/evm/opcodes/return_revert.rs
bus-mapping/src/evm/opcodes/returndatacopy.rs
bus-mapping/src/evm/opcodes/sha3.rs
zkevm-circuits/src/evm_circuit/execution/calldatacopy.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/codecopy.rs
zkevm-circuits/src/evm_circuit/execution/extcodecopy.rs
zkevm-circuits/src/evm_circuit/execution/return_revert.rs
zkevm-circuits/src/evm_circuit/execution/returndatacopy.rs
zkevm-circuits/src/evm_circuit/execution/sha3.rs

Reference go-ethereum function [calcMemSize64WithUint](https://github.com/ethereum/go-ethereum/blob/84c3799e21d61d677965715fe09f8209660b4009/core/vm/common.go#L38), ignore to check Uint64 overflow for memory offset if length is zero.
it is also called by [calcMemSize64](https://github.com/ethereum/go-ethereum/blob/84c3799e21d61d677965715fe09f8209660b4009/core/vm/common.go#LL31C9-L31C30). And both are used for opcodes in [memory_table.go](https://github.com/ethereum/go-ethereum/blob/84c3799e21d61d677965715fe09f8209660b4009/core/vm/memory_table.go#L20) as `memorySize` in [jump_table.go](https://github.com/ethereum/go-ethereum/blob/84c3799e21d61d677965715fe09f8209660b4009/core/vm/jump_table.go#L387).
For Call opcodes, in offset and size are truncated to Uint64 as …

Bug: fix to truncate offset from Word to Uint64 when length is zero for some opcodes

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/circuit_input_builder/tracer_tests.rs
bus-mapping/src/error.rs
bus-mapping/src/evm/opcodes.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/step.rs

**NOTE: This is an updated version of https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1357**
This PR is actually based on top of #1419
#1130 
Error types for insufficient balance and nonce overflow. These are supporting changes required for the CREATE/CREATE2 opcodes' gadget.
The above errors will be handled within the CREATE/CREATE2 opcodes' gadget. In case of insufficient balance, it is also handled in the CallOp gadget for call related opcodes.

Feat/CREATE Part B - Error cases that will be handled within opcode gadgets

---

integration-tests/src/integration_test_circuits.rs
integration-tests/tests/circuits.rs
zkevm-circuits/src/pi_circuit.rs
zkevm-circuits/src/pi_circuit/dev.rs

This is a very small PR.  While investigating https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1439 I noticed we don't have an integration test for the Public Inputs Circuit, so I just added it.

Add PiCircuit to integration tests

---

gadgets/src/less_than.rs
zkevm-circuits/src/copy_circuit.rs

The PR modifies the assign function of the LtChip to take `Value<F>` input instead of `F`. According to this discussion [Halo2 - Discord](https://discord.com/channels/995022112811135148/1113747239534346250/1113854493646397621) with @therealyingtong and @ed255, it emerged how the current design of the chip makes its usage prone to bugs. 
For example, this is how it is currently used in summa-solvency => https://github.com/summa-dev/summa-solvency/blob/a7d0c1f51c7e146bac2686c432c945ff6f3f063f/src/chips/merkle_sum_tree.rs#L338-L354
In order to extract `F` from an assigned cell, I need to create an if conditional that performs the `assign` function only if a witness value is Some. This is a problem as the assignment function won't be called during keygen.
`cargo test less_than`

fix: modify assign function of LtChip to take `Value<F>` input instead of `F`

---

zkevm-circuits/src/keccak_circuit.rs
zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs
zkevm-circuits/src/table.rs
zkevm-circuits/src/util/word.rs

Support word lo-hi in keccak circuit
#1385 
- Change the keccak circuit hash output format from RLC to word lo-hi.
- Add convenient methods `map` for Word. This can easily map two limbs to other types.
- Add a constructor for the zero known value word.
The following tests can pass if we remove math_gadget tests below
```
cargo test -p zkevm-circuits packed_multi_keccak_simple --features test
```
```
zkevm-circuits/src/evm_circuit/util/math_gadget/add_words.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/cmp_words.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/lt_word.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/min_max_word.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/modulo.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/mul_add_words.rs
```

[word lo/hi] keccak circuit to word

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/error.rs

This PR attempts to associate the function `get_step_reported_error` to `ExecError`.
Resolves #1181 
- [x ] Bug fix (non-breaking change which fixes an issue)
We wanted to move the function `get_step_reported_error` to an `imp ExecError`, I also moved the part related to `OogError` to its own associated function `From<OpCodeId> for OogError`. I changed an if/else block into a match expecting to handle more errors for CREATE/2.
Personally I would update the function `get_step_reported_error` to take as input an `GethExecStep` and in that case directly implement it as a `From<GethExecStep> for ExecError` but the return type should be changed to `Option<ExecError>` since the step may not have an error (step.error is optional).
No tests were added as no new functionalities were added.

Change ExecError related functions to be associated-fns

---

integration-tests/src/integration_test_circuits.rs

Integration tests compare permutations of proofs to check for variadic circuits
[[_link issue here_]](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1220)
- as said
Trivial
Run integration test in PR

Integration tests compare permutations of proofs to check for variadic circuits

---

Cargo.lock
bus-mapping/Cargo.toml
bus-mapping/src/evm.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/calldataload.rs
bus-mapping/src/evm/opcodes/sha3.rs
mock/src/lib.rs
mock/src/sha3.rs
zkevm-circuits/src/copy_circuit/test.rs
zkevm-circuits/src/evm_circuit/execution/sha3.rs

1. Move `Sha3CodeGen` and `rand_bytes` from bus-mapping to mock crate. Since they are only used for test.
2. Delete `rand` dependency for bus-mapping.
`cargo build` fails in `bus-mapping` folder.

Refactor: move `Sha3CodeGen` struct and `rand_bytes` function to mock crate

---

.github/workflows/ci.yml
zkevm-circuits/src/evm_circuit/execution/balance.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_memory_copy.rs
zkevm-circuits/src/evm_circuit/execution/error_write_protection.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/util/int_decomposition.rs

Add back 
- evm_circuit 
- keccak_circuit 
- exp_circuit 
- pi_circuit 
- state_circuit
unittest to ci
Other subcircuit `tx_circuit/copy_circuit/bytecode_circuit/root_circuit` still failed for now, will be fixed in another pr
[N/A](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1487)
- Fix unittest assertion [failed](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/word-lo-hi/zkevm-circuits/src/util/int_decomposition.rs#L39-L43) due to sanity check on address H160 retrieved from U256. We need to clean up MSB 12 bytes to 0 
- add subcircuit light tests on CI in whitelist based

[word lo/hi] add ci subcircuit unit test and fix address assignment 

---

bus-mapping/src/evm/opcodes/calldatacopy.rs
bus-mapping/src/evm/opcodes/codecopy.rs
bus-mapping/src/evm/opcodes/extcodecopy.rs
bus-mapping/src/evm/opcodes/returndatacopy.rs
zkevm-circuits/src/evm_circuit/execution.rs

Fix rw operation mismatch due to not reuse exec_step
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1483
Verify via below command
```
RUST_LOG=DEBUG cargo test --package zkevm-circuits --lib -- evm_circuit::execution::returndatacopy::test evm_circuit::execution::codedatacopy::test  evm_circuit::execution::extcodecopy::test evm_circuit::execution::codecopy::test
```
and no error msg, with all test pass though

fix rw operation mismatch and reuse exec_step

---

zkevm-circuits/src/bin/stats/main.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/instrumentation.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/dev.rs
zkevm-circuits/src/state_circuit/lookups.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/table.rs
zkevm-circuits/src/table/ux_table.rs
zkevm-circuits/src/witness/block.rs

[_PR description_]
Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1426
Depends by https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1414

[word lo/hi] support u16 range lookup 

---

mock/src/block.rs

Implement compute block hash in mock/block.rs
#1198 
- Adding the implementation and test the block hash header
The code is quite straight forward, I tried to follow specifications + trial and errors.
A test was added within mock/src/block.rs

Implement header hash block

---

bus-mapping/src/circuit_input_builder.rs
circuit-benchmarks/src/pi_circuit.rs
integration-tests/run.sh
integration-tests/src/integration_test_circuits.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/instance.rs
zkevm-circuits/src/lib.rs
zkevm-circuits/src/pi_circuit.rs
zkevm-circuits/src/pi_circuit/dev.rs
zkevm-circuits/src/pi_circuit/param.rs
zkevm-circuits/src/pi_circuit/test.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/tx_circuit.rs
zkevm-circuits/src/util/word.rs
zkevm-circuits/src/witness/block.rs

replace rand/rlc by pure keccak hashing
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1344
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1383
- replace rpi rand/rlc logic by pure hashing 
- simplify public input into just 2 fields: digest[0:16] as `hi`, and digest[16:32] as `lo`, while `digest = Keccak(<public data>)`
- adopt word-lo-hi
nitpick
- prefix table column annotation with table name for better debugging

[word lo/hi] pi circuit replace rand/rlc by keccak hash

---

zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/super_circuit/test.rs

[_PR description_]
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1499
This pr is to rewrite/split copy circuit constrains to trade more gates with less degree.
copy table `tag` field is binary number decomposition with degree N (N represent number of bits, in copy table case N = 3). Once put in `or::expr([#num_or_condition])`, gate degrees will be exploded quickly by `N*#num_or_condition`.  
Before PR, copy circuit max is degree 12, 
After PR,  copy circuit max 6 degree with 2 more gates. 
However, circuit degree upper bound still increase by 1 (9 -> 10) for word-lo-hi refactor, due to state-circuit `batch_is_zero-"is_zero is 1 if values are all zero">`  gate degrees from 6 -> 10 Due to we fold 2 extra column, each contribute 2 degrees …

[word-lo-hi] fine tune copy circuit to reduce degree

---

zkevm-circuits/src/evm_circuit/execution/calldataload.rs
zkevm-circuits/src/evm_circuit/util/memory_gadget.rs

In the BufferReaderGadget, there are two conflicting mechanisms that enforces the zero padding, one based on `selectors`, and one based on `bound_dist`. This causes the issue #1484. This PR fixes this and improves performance at the same time.
#1484 
- Remove the columns `bound_dist` and everything related to it.
- Repurpose the unused `selectors` and add constraints to it.
- The buffer length is taken as the sum of selectors, and compared to the length implied by the start and end addresses.
- The cases where `start < end` and `end <= start` are supported explicitly.
- The length is capped between 0 and the max buffer size using the existing MinMaxGadget. A single MinMaxGadget is used thanks to a `select`.
- Remove the unused methods `has_data` and `num_bytes`.
The simplest fix would be …

fix-bufferreader: constrain the "in-bound" selectors vs the addresses

---

bus-mapping/src/circuit_input_builder.rs
zkevm-circuits/src/evm_circuit/execution/end_block.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/witness/rw.rs

Fixed rws padding logic and padding error handling.
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1507
- more documentation on padding logic
- fix max_rws calculation
- de-duplicated startop in end_block.tx by skip second one.
- panic instead of confused error log in padding calculation function.

fix rws padding logic and error handling

---

Cargo.lock
bus-mapping/Cargo.toml
bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes/create.rs
bus-mapping/src/state_db.rs
circuit-benchmarks/Cargo.toml
eth-types/Cargo.toml
eth-types/src/geth_types.rs
integration-tests/Cargo.toml
integration-tests/src/bin/gen_blockchain_data.rs
mock/Cargo.toml
mock/src/block.rs
mock/src/transaction.rs
testool/Cargo.toml
testool/src/statetest/executor.rs
testool/src/statetest/json.rs
testool/src/statetest/spec.rs
testool/src/statetest/yaml.rs
zkevm-circuits/Cargo.toml

Change ethers-rs related packages from 0.17.0 to 2.0.7
#1451
We need nothing more than simply upgrading the package.

Fix #1451, option 1: Simply upgrade ethers

---

zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/util.rs

Remove evm_word challenge and optimize from 3->2 phase in dev phase.
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1516

optimize few subcircuit synthesis call phase from 3->2 in dev mode

---

zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/step.rs
zkevm-circuits/src/evm_circuit/table.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/lib.rs
zkevm-circuits/src/table/keccak_table.rs
zkevm-circuits/src/test_util.rs
zkevm-circuits/src/witness/rw.rs

- rm deprecated, unreachable_code
- doc some parts.
part of  #1494

Remove  deprecated, unreachable_code and add docs to Evm circuit

---

.github/workflows/integration.yml
.github/workflows/labeler.yml
.github/workflows/lints.yml
.github/workflows/main-tests.yml
.github/workflows/test-features.yml

- Remove bitrot task which was building the benchmarks and examples but we don't have any
- Merge cargo fmt, clippy and doc links into a single job to reduce noise
- Split heavy tests and light tests into two jobs to parallelize the work
- Merge all feature tests into a single job to reduce noise.
- Disable integration tests on pull requests because they are taking a long time currently.  Enable them only when the trigger-integration-test label is set, when they are scheduled via cron, or when pushing to main.
---
- Times before: 57 minutes
- Longest: Integration tests: 57 min
- Second longest: Tests: 28 min
- Times now: 19 minutes
- Longest: Light unit tests: 19 min
- Second longest: Heavy unit tests: 16 min

Clean up github workflows

---

.github/workflows/main-tests.yml

Remove the matrix strategy in the build job and instead hardcode the build target.  Since we only have 1 target we don't need the matrix strategy.
This is a small PR aimed to clean up the output of jobs running from commits merged to main.  Our configuration skips jobs that have already run, and when this happens, the matrix strategy is not resolved and we see this:
By removing the matrix strategy we should see a cleaner output.

Hardcode build target in workflow

---

zkevm-circuits/src/evm_circuit/execution/push.rs
zkevm-circuits/src/evm_circuit/execution/stop.rs

We intend here to support PUSHn with bytecode length inferior to n.
Issue #633 
Linked to specs issue https://github.com/privacy-scaling-explorations/zkevm-specs/issues/463
- Update push.rs to support bytecode of size smaller than n
- Update stop.rs similarly
In pushn, "selectors" are switches to enable or disable lookup arguments on the bytcode bytes as well as to check whether these are non-null if needs be. They directly depend on "n" of PUSHn.
We add to these "selectors", "counters" which have similar role but are a subset of them depending on the bytecode length. We added these extra switches to be able to easily check the various identities at the risk of some redundancy.
To support these changes, modifications in stop.py also had to be done. More precisely, the check …

Fully implement PUSHn

---

zkevm-circuits/src/evm_circuit/step.rs

We don't need to match `OpcodeId::PUSH32` again, because it has been contained in previous code.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/b36da2a4047f8811990c6d928bb1e1864f88328b/zkevm-circuits/src/evm_circuit/step.rs#L215-L216
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/b36da2a4047f8811990c6d928bb1e1864f88328b/eth-types/src/evm_types/opcode_ids.rs#L319-L321
The `is_push` contains the `PUSH32` opcode. So, let's remove the duplicate match.
No

fix: remove unnecessary match

---

zkevm-circuits/src/evm_circuit/execution/callop.rs

Manually counting read-write indices is error-prone. We use the `StepRws` struct to automatically track read-write indices.
This PR is motivated by trying to fix #1565. Unfortunately, this PR alone doesn't fix #1565.

use StepRws to make rw index less error prone

---

bus-mapping/src/evm/opcodes/callop.rs
zkevm-circuits/src/evm_circuit/execution/balance.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/create.rs
zkevm-circuits/src/evm_circuit/execution/end_tx.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution/extcodecopy.rs
zkevm-circuits/src/evm_circuit/execution/extcodehash.rs
zkevm-circuits/src/evm_circuit/execution/extcodesize.rs
zkevm-circuits/src/evm_circuit/execution/shl_shr.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/lt_word.rs
zkevm-circuits/src/witness/block.rs
zkevm-circuits/src/witness/rw.rs

Continuing on #1565, which was closed accidentally and Github doesn't allow me to reopen because the branch was removed.
The cause of the test failure is the inconsistent read-write to the read-write table between circuit assignment and busmapping. 
#1584
- Fix the account read and write in callop with non-zero values. 
- Enable ignored callop tests
- Improve the account read-write table API. So that we don't mistakenly read the account hash when we intend to read the account balance.
- Expose the lt_word gadget assignment output
- Improve the debug messages
- Various readability fixes
```
cargo test -p zkevm-circuits callop_simple -- --nocapture 
```
New debug message
```
> Step Op(PUSH32)
94 READ Stack { rw_counter: 94, is_write: true, call_id: 1, stack_pointer: 1018, value: …
```

Fix callop tests and some improvements

---

bus-mapping/src/evm/opcodes/sload.rs
bus-mapping/src/evm/opcodes/sstore.rs
zkevm-circuits/src/evm_circuit/execution/sload.rs
zkevm-circuits/src/evm_circuit/execution/sstore.rs

This PR fixes the soundness problem in the implementation of SLOAD and SSTORE opcodes by adding constraints to the `is_warm` cell. The problem is detailed in issue #1049.
#1049
- Update `bus-mapping/src/evm/opcodes/sload.rs`
- Update `bus-mapping/src/evm/opcodes/sstore.rs`
- Update `zkevm-circuits/src/evm_circuit/execution/sload.rs`
- Update `zkevm-circuits/src/evm_circuit/execution/sstore.rs`
The current implementation of SSTORE and SLOAD didn't constrain the `is_warm` cell, which could result in any value and lead to soundness problems. This PR adds constraints to the `is_warm` cell in order to ensure correctness.
-

fix unconstrained is_warm in sload/sstore

---

zkevm-circuits/src/evm_circuit/execution/end_tx.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs

fix end_tx circuit coinbase transfer
https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/6180463331/job/16776966002?pr=1581
- add rw_delta to TransferTo
N/A
previous failed unit test passed

[fix] end_tx circuit coinbase transfer

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/begin_end_tx.rs

resolves https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1612
- [_item_]
tested with thousands of mainnet blocks (in scroll fork mainnet.rs tool)

bus-mapping: improve self-destruct

---

README.md
zkevm-circuits/src/circuit_tools/cached_region.rs
zkevm-circuits/src/circuit_tools/cell_manager.rs
zkevm-circuits/src/circuit_tools/constraint_builder.rs
zkevm-circuits/src/circuit_tools/memory.rs
zkevm-circuits/src/mpt_circuit.rs
zkevm-circuits/src/mpt_circuit/account_leaf.rs
zkevm-circuits/src/mpt_circuit/branch.rs
zkevm-circuits/src/mpt_circuit/extension.rs
zkevm-circuits/src/mpt_circuit/extension_branch.rs
zkevm-circuits/src/mpt_circuit/helpers.rs
zkevm-circuits/src/mpt_circuit/param.rs
zkevm-circuits/src/mpt_circuit/rlp_gadgets.rs
zkevm-circuits/src/mpt_circuit/start.rs
zkevm-circuits/src/mpt_circuit/storage_leaf.rs
zkevm-circuits/src/mpt_circuit/witness_row.rs

Some small improvements to the MPT circuit. Most notably:
- Added a check that the RLP encoding of the RLP values are minimal (no leading zeros) in the main RLP value decoding unit
- Fixed bug: byte lookups were not generated correctly
- Some other misc small improvements
- [_item_]
- All MPT tests run
- make test-all

[MPT] Add minimal RLP encoding check

---

eth-types/src/evm_types/opcode_ids.rs

0xb3 / 0xb4 are rendered as "TLOAD/TSTORE" in geth trace json.

fix: parse "TLOAD/TSTORE" correctly in trace

---

bus-mapping/src/circuit_input_builder.rs
circuit-benchmarks/src/bytecode_circuit.rs
zkevm-circuits/src/bytecode_circuit.rs
zkevm-circuits/src/bytecode_circuit/test.rs

- Remove minimal_rows 
- Configure the bytecode circuit with the circuit degree instead of size.
#1607
[x] Bug fix (non-breaking change which fixes an issue)
Please review this after #1632 is merged.

Remove minimal_rows in the Bytecode circuit

---

Cargo.lock
testool/src/statetest/executor.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/src/evm_circuit/execution/addmod.rs
zkevm-circuits/src/evm_circuit/execution/gas.rs
zkevm-circuits/src/evm_circuit/execution/mulmod.rs
zkevm-circuits/src/test_util.rs

1. Capture the error detail of the unsatisfied circuit from CircuitTestBuilder 
2. Split the body of CircuitTestBuilder::run() into 3 methods for readability.
3. Revamp the error handling in CircuitTestBuilder
#1637  
The error handling has been a pain point for us for a long time. 
The design of error handling in this PR is heavily inspired by [this blog post](https://mmapped.blog/posts/12-rust-error-handling.html).

Fix circuit failure output

---

bus-mapping/src/evm/opcodes/begin_end_tx.rs
eth-types/src/evm_types.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/util.rs
zkevm-circuits/src/witness/block.rs

We upstream scroll's precompile handling in bus mapping so that the EVM circuit warms the precompile addresses at the beginning of the transaction.
#1626
- Warm precompile addresses
- Fix some minor issues in StepRws offset and the Rws debugging messages.

Add precompile contracts' addresses to the access list

---

bus-mapping/src/circuit_input_builder/block.rs
bus-mapping/src/evm/opcodes/stackonlyop.rs
eth-types/src/geth_types.rs
geth-utils/gethutil/trace.go
mock/src/lib.rs

feat: support prevrandao

---

testool/src/statetest/yaml.rs
zkevm-circuits/src/bin/stats/helpers.rs
zkevm-circuits/src/mpt_circuit.rs

During the review of the codebase, I found some nitpicks in Options and pattern matching. Here's a quick PR to improve readability.
Nitpick
- Nested conditions hurt readability, match patterns when possible
- unwrapping Options inside a branch beats the purpose of Options

Nitpicks: is_some() refactor

---

zkevm-circuits/src/table/block_table.rs

block_table `tag`, `index` those 2 value are not only non-constrained but also be advice column, which means the `tag`, `index` can be witness in any value/order and lead to a situation of lookup blocktag under wrong value. E.g. use `timestamp` value to represent `base_fee`. 
Block_table `value` column is constrained by public input so there is no such issue.
Since `block_table` per row are pre-defined, this PR fixed soundness by move `tag`, `index` to fixed column, so value will be encoded in verify key and avoid malicious manipulation.
Folk Scroll previously has similar fixed https://github.com/scroll-tech/zkevm-circuits/commit/d3922e1d2b3188a04b39d90cdacd22f83cb4dde0#diff-632aa6def09f1668ecdf89781dbf23c2c3cf3bc379209b19cce79abd0a1d0bfe
N/A

fix soundness: block_table tag/index should be fixed column

---

zkevm-circuits/src/evm_circuit/util/constraint_builder.rs

This works
```rust
cb.step_first(|cb| {
cb.require_equal("xxxxx", A, B); // it works!
});
```
However it doesnt works on any lookup wrap by step, e.g.
```rust
cb.step_first(|cb| {
cb.call_context_lookup_write(Some(call_id.expr()), field_tag, value); // lookup will happen on any step other than step 1
});
```
The reason is because lookup constraints expression not including location selector when query lookup cell.
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/util/constraint_builder.rs#L1489-L1496
While the location selector are created in execution.rs at later phase 
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/09651d40afc59462fd943e9789be8f8b0ccb90d9/zkevm-circuits/src/evm_circuit/execution.rs#L731-L757 …

add error pruning on step_first/step_last to avoid use against lookup

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs

geth_step.error is not enough. It only contains error inside geth trace, only stack err and oog err. Exec_step.error contains all types of err we recovered during parsing trace.
This pr will fix some failures of testool, like `CreateOOGFromCallRefunds_d1(SStore_Refund_OoG)_g0_v0`

fix return/revert offset/len in handle_return for err cases

---

bus-mapping/src/circuit_input_builder.rs

this is a minor PR to remove duplicate entries for keccak circuit.

opt: dedup inputs for keccak circuit

---

gadgets/src/permutation.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/constraint_builder.rs
zkevm-circuits/src/state_circuit/test.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/util.rs
zkevm-circuits/src/util/chunkctx_config.rs
zkevm-circuits/src/witness/rw.rs

Depends on #1641 with extra commit: adding fingerprint equality check on chronological/by address rw_table
Fingerprint check gate will be enable in last chunk last row
chunk ctx
- [current chunk index, total chunk, initial rwc] // equal with chunk_{i-1}
- [next chunk index, total chunk, next rwc] equal with chunk_{i+1}
pi circuit
- [pi digest lo, pi digest hi] // same across all chunks
state circuit
- [prev permutation fingerprint] // equal with chunk_{i-1}
- [next permutation fingerprint] // equal with chunk_{i+1}
- [alpha, gamma] // same across all chunks
evm circuit
- [prev permutation fingerprint] // equal with chunk_{i-1}
- [next permutation fingerprint] // equal with chunk_{i+1}
- [alpha, gamma] // same across all chunks

[proof-chunk] check rwtable fingerprint equality in last chunk

---

zkevm-circuits/src/witness/block.rs

Integration Tests have been failing since introduction of https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1369, due to Option::Unwrap on None value, when eth_block.withdrawals==None. 
- zkevm-circuits/zkevm-circuits/src/witness/block.rs
replace eth_block.withdrawals.clone().unwrap() with eth_block.withdrawals.clone().unwrap_or_default()
https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/6968928576/job/18963801769
<hr>
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1687

Fix circuits integration tests panic: "unwrap on None value" when EIP-4896 withdrawals==None

---

circuit-benchmarks/src/bytecode_circuit.rs
circuit-benchmarks/src/copy_circuit.rs
circuit-benchmarks/src/evm_circuit.rs
circuit-benchmarks/src/exp_circuit.rs
circuit-benchmarks/src/mpt_circuit.rs
circuit-benchmarks/src/packed_multi_keccak.rs
circuit-benchmarks/src/pi_circuit.rs
circuit-benchmarks/src/state_circuit.rs
circuit-benchmarks/src/super_circuit.rs
circuit-benchmarks/src/tx_circuit.rs

This PR aims to get the benchmark tests running.
#1646
- Updates default degree in the benchmark tests
```
cargo test --release --features=benches bytecode
cargo test --release --features=benches copy
cargo test --release --features=benches evm
cargo test --release --features=benches exp
cargo test --release --features=benches mpt
cargo test --release --features=benches keccak
cargo test --release --features=benches pi
cargo test --release --features=benches state
cargo test --release --features=benches super
cargo test --release --features=benches tx
```

Fix circuit benchmarks

---

circuit-benchmarks/src/state_circuit.rs
gadgets/src/permutation.rs
integration-tests/src/integration_test_circuits.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/root_circuit.rs
zkevm-circuits/src/root_circuit/aggregation.rs
zkevm-circuits/src/root_circuit/dev.rs
zkevm-circuits/src/root_circuit/test.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/dev.rs
zkevm-circuits/src/state_circuit/test.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/test_util.rs
zkevm-circuits/src/util/chunkctx_config.rs
zkevm-circuits/src/witness/block.rs
zkevm-circuits/src/witness/rw.rs

covered item
TODO
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1603
Light tests pass.
integration test failed due to challenge computation in witness not implemented yet, which will be done in bus mapping chunk PR.

[proof chunk] root circuit consistency between chunk

---

eth-types/src/evm_types/memory.rs
eth-types/src/evm_types/opcode_ids.rs
eth-types/src/sign_types.rs

Hello I am learning web3 programming, I went through some of the code because I was told zk is fascinating (and it is). I found some little errors in comments, nothing important. I hope you don't mind opening a PR for such a little thing, I read the contributing file and didn't find it being forbidden, but even if it is little I hope i'll help you even just a bit in your research. Thank you for making that repo public. Have a nice day.

Grammatical corrections in eth-types

---

bus-mapping/src/evm/opcodes/begin_end_tx.rs
zkevm-circuits/src/evm_circuit/execution/end_tx.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/tx.rs
zkevm-circuits/src/test_util.rs

This PR fix soundness by sharing txid write lookup between current step and next step
#1707 
Before fix, `cur_end_tx -> callcontext(txid, WRITE)` vs `next_begin_tx -> callcontext(txid, WRITE)` are meant to constraint `next_tx_id = cur_tx_id + 1`. However, because 2 callcontext write are different records in rw_table, so actually second record are under-constraint and tx_id can be manipulated. 
Because so far we do not have negative test framework. So this PR just simply adding a simple positive test to assure there is no consecutive tx_id write with SAME tx_id.
If this fix make sense, will update zkevm-specs accordingly https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm_circuit/execution/end_tx.py#L71-L79

fix soundness: share txid write lookup across step

---

Cargo.toml
integration-tests/Cargo.toml
light-client-poc/Cargo.toml

Cargo defaults to `resolver = "2"` in edition 2021 only for singular crates. Workspace tho defaults to the old `resolver = "1"` and will override this setting for all crates in the workspace. [The guideline](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace) is to manually set the `resolver = "2"` on workspace level.
This was documented recently and since a few releases produces a warning on building. You don't see it due to the `rust-toolchain` setting.
- specifies `resolver = "2"` on workspace level
- removes `resolver = "2"` from light-client-poc/Cargo.toml because it was ignored anyway
This also fixes this warning:
```
warning: resolver for the non root package will be ignored, specify resolver at the workspace root:
package: …
```

chore: set resolver v2 at the workspace level

---

zkevm-circuits/src/circuit_tools/cached_region.rs
zkevm-circuits/src/circuit_tools/cell_manager.rs
zkevm-circuits/src/circuit_tools/constraint_builder.rs
zkevm-circuits/src/circuit_tools/memory.rs

This change optimizes memory allocations in `circuit-tools`. Where possible pre-allocates needed memory and removes some unneeded clones.
- preallocating or bulk resizing with `.reserve()`, `.with_capacity()` and `.resize()` or collecting
- some clones removals
This should increase performance a bit
```
cargo test -p zkevm-circuits
```

perf(circuit-tools): preallocate memory and remove unnecessary clones

---

.github/workflows/wasm.yml
Cargo.lock
bus-mapping/Cargo.toml
bus-mapping/src/lib.rs
bus-mapping/src/precompile.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/src/lib.rs

zkevm-circuits can be used in WASM to verify zkEVM proofs in the browser.
While compiling zkevm-circuits crate for WASM target, the following crate gives issues:
- revm-precompile: used by bus-mappings while generating witnesses
- snark-verifier: used in the root_circuit
Since use-case is to just verify proofs, `revm-precompile` dependency can be removed during WASM compilation. And for SuperCircuit, `snark-verifier` dependency can be removed. It should be easy to add support for root_circuit too, by adding the WASM support to `snark-verifier` crate such that it exposes required rust objects in WASM mode.
- I tried to have this without using rust features, i.e. using target arch conditional compilation, but toggling optional dependencies with target arch seems to be very tricky. Hence, …

WASM support for zkevm-circuits crate

---

zkevm-circuits/src/evm_circuit/execution/end_tx.rs
zkevm-circuits/src/evm_circuit/execution/invalid_tx.rs
zkevm-circuits/src/evm_circuit/util/tx.rs

This PR is aimed to do minor style refactor/fix of #1719
#1725 
This PR addresses issue #1725 to do a minor style fix, that @lispc mentioned [here](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1719#issuecomment-1880469834)

refactor(evm_circuit): minor fix in end_tx (#1725)

---

Cargo.lock
gadgets/Cargo.toml
geth-utils/Cargo.toml
integration-tests/Cargo.toml
light-client-poc/Cargo.toml
testool/src/statetest/mod.rs
testool/src/statetest/yaml.rs
zkevm-circuits/src/evm_circuit/execution/addmod.rs
zkevm-circuits/src/evm_circuit/execution/mulmod.rs
zkevm-circuits/src/evm_circuit/test.rs
zkevm-circuits/src/evm_circuit/util.rs

We removed the warning message shown during the project build.
```
warning: the following packages contain code that will be rejected by a future version of Rust: traitobject v0.1.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
```
The message is caused by an unused dependency introduced during #1615
None
- Removed some unused dependencies
- Removed some unused imports
Local build on all targets

Dependency cleaning round

---

circuit-benchmarks/src/mpt_circuit.rs
light-client-poc/src/circuit/mod.rs
light-client-poc/src/circuit/state_update.rs
light-client-poc/src/server.rs
light-client-poc/src/tests/mainnet.rs
light-client-poc/src/utils.rs
zkevm-circuits/src/mpt_circuit.rs

This PR resolves the test failure in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1706.
The parameter `max_nodes` has been added to the MPT to have always the same fixed column `q_enable`.
The fixed column `q_last` has been removed because it is not necessary - if some nodes are added to the MPT proof after the account/storage leaf to enable some non-valid lookups, the proof would fail because of address/key RLC constraints (the RLC is being built node by node).
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1700

MPT max nodes

---

bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/mock.rs
zkevm-circuits/src/bin/stats/main.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/invalid_tx.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/test_util.rs
zkevm-circuits/src/evm_circuit/util/memory_gadget/test_util.rs
zkevm-circuits/src/evm_circuit/util/tx.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/super_circuit/test.rs
zkevm-circuits/src/test_util.rs
zkevm-circuits/src/witness/block.rs

We add an initial structure for runtime config. In this PR, we plan to add only the invalid tx configuration for the starter.
#1636 
New feature (non-breaking change which adds functionality)
- Allow Geth to take invalid tx. The config doesn't affect geth util

Runtime config

---

eth-types/src/lib.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/create.rs
zkevm-circuits/src/evm_circuit/execution/end_block.rs
zkevm-circuits/src/evm_circuit/execution/error_precompile_failed.rs
zkevm-circuits/src/evm_circuit/execution/error_write_protection.rs
zkevm-circuits/src/evm_circuit/execution/stop.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/mpt_circuit/account_leaf.rs
zkevm-circuits/src/mpt_circuit/branch.rs
zkevm-circuits/src/mpt_circuit/extension.rs
zkevm-circuits/src/mpt_circuit/extension_branch.rs
zkevm-circuits/src/mpt_circuit/helpers.rs
zkevm-circuits/src/mpt_circuit/start.rs
zkevm-circuits/src/mpt_circuit/storage_leaf.rs
zkevm-circuits/src/util/word.rs

to address discussion in PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1748
implement OpsIdentity for word<T> so that we no longer need to type hint `::<Expression<F>>` or `::<F>` every time.

Ops id trait

---

zkevm-circuits/src/circuit_tools/memory.rs
zkevm-circuits/src/mpt_circuit.rs
zkevm-circuits/src/util/cell_placement_strategy.rs

Change HashMap to BTreeMap in memory.rs and in cell_placement_strategy.
#1700
- fix in memory.rs
- fix in cell_placement_strategy
Generates different circuit keys making proof verification fail for different witnesses.
Manual testing.

fix nondeterministic constraint generation

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes/begin_end_tx.rs
bus-mapping/src/evm/opcodes/callop.rs
bus-mapping/src/evm/opcodes/create.rs
zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/callop.rs
zkevm-circuits/src/evm_circuit/execution/create.rs
zkevm-circuits/src/evm_circuit/execution/end_tx.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs

- Transfer and TransferWithGas gadgets are mostly the same. We can merge them and duplicate them.
- There are duplicated logics for creating the receiver account (writing empty hash). We remove the duplicated one.
- The update balance gadget is vague, it is hard to understand whether we want to add or subtract balance. We extract a helpful method for that.
- deduplicate the transfer_to logic in busmapping.
- Fix the receiver creation condition on busmapping.
- Fix the order of the sender account read-write in begin tx assignment.
Thank @curryrasul for initializing this conversation.
Refactor (no updates to logic)
```
cargo test -p zkevm-circuits create
cargo test -p zkevm-circuits begin_tx
cargo test -p zkevm-circuits end_tx 
```

Merge Transfer and TransferWithGas gadget

---

geth-utils/gethutil/mpt/trie/stacktrie.go
geth-utils/gethutil/mpt/witness/gen_witness_transactions_test.go

closed #1752 
- Adding different numbers of txs to test different trie status (e.g. one leaf only, one ext. , one branch and one leaf ...etc)
- Fixing `GetProof` (if input is an ext node, it always assign first child of the root ext. node, `st.children[0]`)
- Fixing `getNodeFromBranchRLP` (if input is an leaf, it could throw an exception)
- Refactoring `getNodeFromBranchRLP`
#1752

Feat/#1752 fix witness generation - adding testing

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes/error_write_protection.rs
bus-mapping/src/operation/container.rs
zkevm-circuits/src/evm_circuit/execution/error_write_protection.rs
zkevm-circuits/src/evm_circuit/execution/tstore.rs

The bus mapping TSTORE did not handle the cases where the opcode's effect is revert and the error that happens if TSTORE is called in a static call. This adds tests for those two cases and then fixes the bus mapping.
Added tests that fail before the bus mapping fixes are applied.
```
- [Add failing revert test](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1811/commits/be4b13dd1251a370456c6ed86f04226af48aea08)
- [Add failing write protection test for TStore](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1811/commits/18845eb1a5fd624bddb0ac626c22a5d32389ea8f)
- [Handle reverts and write protection failure for TSTORE in bus mapping](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1811/commits/01050195879550fa68d …
```

Fix TStore for reverts and in static calls

---

.github/workflows/config/typos.toml
.github/workflows/typos.yml
bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/circuit_input_builder/tracer_tests.rs
geth-utils/gethutil/mpt/trie/committer.go
geth-utils/gethutil/mpt/trie/trie.go
geth-utils/gethutil/mpt/witness/gen_witness_from_infura_blockchain_test.go
testool/src/statetest/executor.rs
testool/src/statetest/json.rs
testool/src/statetest/results.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/abs_word.rs
zkevm-circuits/src/evm_circuit/util/memory_gadget.rs
zkevm-circuits/src/mpt_circuit/account_leaf.rs
zkevm-circuits/src/root_circuit.rs
zkevm-circuits/src/tx_circuit.rs
zkevm-circuits/src/util/word.rs

- `advices` -> `advice` but It has appeared many times,Fear of side effects from excessive changes, this PR do not process this typo for now
- `extend-exclude = ["integration-tests/contracts"]`  is third party lib
close:https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1781

Add typos tool to CI to automate typo detection
