Cargo.toml
src/gadget.rs
src/gadget/evm_word.rs

8 bit word encoding

---

zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/op_execution.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic.rs
zkevm-circuits/src/evm_circuit/op_execution/push.rs

Evm circuit push

---

bus-mapping/Cargo.toml
bus-mapping/README.md
bus-mapping/src/error.rs
bus-mapping/src/evm.rs
bus-mapping/src/evm/memory.rs
bus-mapping/src/evm/opcodes/mload.rs
bus-mapping/src/evm/stack.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/exec_trace/exec_step.rs
bus-mapping/src/exec_trace/parsing.rs
bus-mapping/src/lib.rs
bus-mapping/src/macros.rs
bus-mapping/src/operation.rs
zkevm-circuits/src/state_circuit/state.rs

Resolves: #94
Resolves: #90
Resolves: #84
#96 is out of the scope of this PR but will be addressed in a follow-up one.
Co-authored by @han0110

Change `EvmWord` layout and improve `Memory` and `Stack` APIs

---

zkevm-circuits/src/evm_circuit/op_execution.rs
zkevm-circuits/src/evm_circuit/op_execution/pop.rs

Implement opcode POP

---

bus-mapping/src/evm/opcodes/mload.rs
bus-mapping/src/evm/opcodes/push.rs
bus-mapping/src/exec_trace.rs
bus-mapping/src/operation.rs
zkevm-circuits/src/state_circuit/state.rs

 Update MemoryOp to contain a single byte per value 

---

bus-mapping/src/evm.rs

Fix the warning that appears in other PRs https://github.com/appliedzkp/zkevm-circuits/pull/97/files#diff-7b072fa82d7fe486f5bd38e48d4922a4a77f322846aaa47163cc90f86b3eee64

fix lint warnings

---

zkevm-circuits/src/state_circuit/state.rs

The constraint for the first stack operation when (stack) address changes to be write is now removed as this is enforced by EVM circuit.

First stack op constraint removed

---

zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/op_execution.rs
zkevm-circuits/src/evm_circuit/op_execution/memory.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/constraint_builder.rs

Spec: https://github.com/appliedzkp/zkevm-specs/pull/69

Implement MSTORE8 opcode

---

bus-mapping/src/operation.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/op_execution.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic/add.rs
zkevm-circuits/src/evm_circuit/op_execution/arithmetic/bitwise.rs
zkevm-circuits/src/evm_circuit/op_execution/byte.rs
zkevm-circuits/src/evm_circuit/op_execution/comparator.rs
zkevm-circuits/src/evm_circuit/op_execution/dup.rs
zkevm-circuits/src/evm_circuit/op_execution/jump.rs
zkevm-circuits/src/evm_circuit/op_execution/jumpdest.rs
zkevm-circuits/src/evm_circuit/op_execution/jumpi.rs
zkevm-circuits/src/evm_circuit/op_execution/memory.rs
zkevm-circuits/src/evm_circuit/op_execution/pc.rs
zkevm-circuits/src/evm_circuit/op_execution/pop.rs
zkevm-circuits/src/evm_circuit/op_execution/push.rs
zkevm-circuits/src/evm_circuit/op_execution/signextend.rs
zkevm-circuits/src/evm_circuit/op_execution/swap.rs
zkevm-circuits/src/evm_circuit/op_execution/utils.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/common_cases.rs
zkevm-circuits/src/evm_circuit/op_execution/utils/constraint_builder.rs

The JUMP spec can be found at https://github.com/appliedzkp/zkevm-specs/pull/67

JUMP and JUMPI opcode circuit

---

keccak256/src/gates/rho_checks.rs
keccak256/src/gates/tables.rs

I forgot to enable selectors in ChunkRotateConversionConfig and BlockCountAccConfig 🙈
enable selectors and fix the test

enable rho check selectors

---

keccak256/Cargo.toml
keccak256/src/arith_helpers.rs
keccak256/src/circuit.rs
keccak256/src/gates.rs
keccak256/src/gates/absorb.rs
keccak256/src/gates/iota_b13.rs
keccak256/src/gates/iota_b9.rs
keccak256/src/gates/mixing.rs
keccak256/src/gates/pi.rs
keccak256/src/gates/rho.rs
keccak256/src/gates/rho_checks.rs
keccak256/src/gates/theta.rs
keccak256/src/gates/xi.rs
keccak256/src/keccak_arith.rs
keccak256/src/lib.rs

The KeccakFConfig contains all of the gadget configurations of the
gadgets plus the logic for the allocations of each of the keccak steps
on each of the regions.

Build keccak all toghether

---

keccak256/src/gates/rho.rs
keccak256/src/gates/rho_checks.rs

use (Cell, F) for Rho gate

---

keccak256/src/gates/theta.rs

As stated in #219, the gates need to apply copy constraints between the
input cells and the witnessed values to ensure correctness between
keccak steps.
Also, now the state_assignation fn returns `out_state` as `[(Cell,F);25]` instead of simply the `F` values.

Update Theta to copy state Cells for in/out

---

.github/workflows/ci.yml
.github/workflows/integration.yml
.github/workflows/lints.yml
bus-mapping/src/evm/opcodes/jump.rs
bus-mapping/src/evm/opcodes/jumpi.rs

Set github actions to trigger also on push to main.

Fix compilation error

---

keccak256/src/gates/rho.rs
keccak256/src/gates/rho_checks.rs
keccak256/src/gates/tables.rs

Move this to an independent PR for better reviewability of #215

use table columns

---

Cargo.lock
Cargo.toml
integration-tests/src/bin/gen_blockchain_data.rs

close https://github.com/appliedzkp/zkevm-circuits/issues/233

bring back ethers deps to crates.io

---

keccak256/src/circuit.rs
keccak256/src/common.rs
keccak256/src/gates/iota_b13.rs
keccak256/src/gates/iota_b9.rs
keccak256/src/gates/mixing.rs
keccak256/src/gates/tables.rs
keccak256/src/keccak_arith.rs

This fixes all the errors in the Mixing config and also introduces the base conversion inside of it.

Fix MixingConfing w/ Lookups integration

---

keccak256/src/gates/mixing.rs

Remove duplicate ROUND_CTANT input from Mixing

---

keccak256/src/gates/mixing.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/signed_comparator.rs
zkevm-circuits/src/evm_circuit/witness.rs

Implement the circuit for SLT / SGT. The spec PR is at https://github.com/appliedzkp/zkevm-specs/pull/95

Signed comparator gadget: SLT, SGT

---

.github/proverCiScripts/deployToProver.sh
.github/proverCiScripts/execBench.sh
.github/proverCiScripts/getSysstat.sh
.github/proverCiScripts/prepareProver.sh
.github/proverCiScripts/rsSysstat.sh
.github/proverCiScripts/shutdownProver.sh
.github/proverCiScripts/wakeUpProver.sh
.github/workflows/gh-actions-prover-benches.yml

This PR aims to merge new workflow file that triggers an evm prover bench test on self-hosted runner (aws ec2). The pipeline invokes a set of custom bash scripts (prover ci scripts) to start and set up the prover environment, execute the bench and collect results (proving time, system stats)

add prover bench scripts and new workflow yml

---

zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/bitwise.rs
zkevm-circuits/src/evm_circuit/execution/signed_comparator.rs
zkevm-circuits/src/evm_circuit/execution/signextend.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs

The CI on the main branch currently fails due to the expr degree exceeding the max degree.
https://github.com/appliedzkp/zkevm-circuits/runs/4881226993?check_suite_focus=true

Fix the error of the expr degree in signed comparator exceeding the max degree

---

bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/calldatasize.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/calldatasize.rs
zkevm-circuits/src/evm_circuit/param.rs

Spec: https://github.com/appliedzkp/zkevm-specs/pull/96

Gadget for opcode calldatasize

---

zkevm-circuits/Cargo.toml
zkevm-circuits/src/evm_circuit.rs

this PR aims to fix issue #359 to improve code debugging experience !

fix unit test debug error 

---

keccak256/src/gates/base_conversion.rs
keccak256/src/gates/rho_checks.rs

Minor: remove comments

---

.github/proverCiScripts/execBench.sh
.github/workflows/gh-actions-prover-benches.yml

This PR extends CI automated circuit benchmarks by introducing state and keccak benches.
For this purpose we will be using the following new labels:
'benchmarks: EVM'
'benchmarks: Keccak'
'benchmarks: State'
'benchmarks: ALL' label is already created, but functionality has not yet been implemented.
Issue URL: https://github.com/appliedzkp/zkevm-circuits/issues/371

Added state and keccak benches according to issue #371

---

zkevm-circuits/src/evm_circuit/execution/end_tx.rs

when block contains >=3 txs. And update tests

Fix incorrect current_cumulative_gas_used in end_tx_gadget

---

Cargo.toml
circuit-benchmarks/Cargo.toml
eth-types/Cargo.toml
gadgets/Cargo.toml
integration-tests/Cargo.toml
keccak256/Cargo.toml
prover/Cargo.toml
zkevm-circuits/Cargo.toml

This is a cosmetic/ergonomic change only.

cargo: patch halo2_proofs on crates.io

---

.github/workflows/integration.yml
bus-mapping/src/evm/opcodes.rs
integration-tests/tests/circuits.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/dummy.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/lib.rs

make sha3 uses dummy gadget; enable erc20 integration tests
fixing https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/440

feat(evm-circuit): add dummy gadget

---

CONTRIBUTING.md
README.md
geth-utils/README.md
zkevm-circuits/src/state_circuit.rs

Just update to latest privacy-scaling-explorations link .

chore: update repo link

---

keccak256/src/permutation.rs
keccak256/src/permutation/circuit.rs
keccak256/src/permutation/generic.rs
keccak256/src/permutation/rho.rs
keccak256/src/permutation/rho_checks.rs

Split #541 and gradually check in the less radical parts.

Add generic to keccak

---

keccak256/src/permutation/circuit.rs
keccak256/src/permutation/iota.rs
keccak256/src/permutation/mixing.rs

Replace iota with generics

---

zkevm-circuits/src/evm_circuit/execution/calldataload.rs

- RLC value
- Add call data offset while indexing

fix: CALLDATALOAD opcode exec

---

zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/not.rs
zkevm-circuits/src/evm_circuit/witness.rs

Prove that input = NOT(output) by showing input XOR output is 255 for every byte.

Add NotGadget

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes.rs
bus-mapping/src/evm/opcodes/stop.rs

Just found and update `begin_tx` `end_tx` `stop` with read/write ops style

bus mapping:  refactor begin&end tx stop with read/write ops

---

zkevm-circuits/src/evm_circuit/execution/gasprice.rs
zkevm-circuits/src/evm_circuit/execution/origin.rs
zkevm-circuits/src/evm_circuit/witness.rs

also remove some ancient functions relared to rw

fix wrong rw lookup in gasprice and origin

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/circuit_input_builder/tracer_tests.rs
zkevm-circuits/src/evm_circuit/step.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs

fix issue #629 and add test for it.
cleanup trace test  `tracer_err_insufficient_balance` useless code and correct comment
cleanup unused `StepRow`

fix issue #629 and  some cleanups

---

circuit-benchmarks/src/state_circuit.rs
integration-tests/tests/circuits.rs
prover/src/compute_proof.rs
zkevm-circuits/src/state_circuit.rs
zkevm-circuits/src/state_circuit/test.rs
zkevm-circuits/src/test_util.rs

state_circuit: move N_ROWS argument to runtime

---

bus-mapping/src/circuit_input_builder/execution.rs
bus-mapping/src/evm/opcodes/calldatacopy.rs
bus-mapping/src/evm/opcodes/codecopy.rs
bus-mapping/src/evm/opcodes/logs.rs
bus-mapping/src/evm/opcodes/sha3.rs
circuit-benchmarks/src/evm_circuit.rs
eth-types/src/evm_types.rs
zkevm-circuits/src/bytecode_circuit/bytecode_unroller.rs
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/calldatacopy.rs
zkevm-circuits/src/evm_circuit/execution/codecopy.rs
zkevm-circuits/src/evm_circuit/execution/logs.rs
zkevm-circuits/src/evm_circuit/execution/sha3.rs
zkevm-circuits/src/evm_circuit/param.rs
zkevm-circuits/src/evm_circuit/table.rs
zkevm-circuits/src/evm_circuit/util/constraint_builder.rs
zkevm-circuits/src/evm_circuit/util/memory_gadget.rs
zkevm-circuits/src/evm_circuit/witness.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/table.rs
zkevm-circuits/src/tx_circuit.rs
zkevm-circuits/src/tx_circuit/sign_verify.rs

SHA3 opcode

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs
bus-mapping/src/evm/opcodes.rs
eth-types/src/evm_types/opcode_ids.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/call.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_constant.rs
zkevm-circuits/src/evm_circuit/execution/jump.rs
zkevm-circuits/src/evm_circuit/execution/jumpi.rs
zkevm-circuits/src/evm_circuit/execution/memory.rs
zkevm-circuits/src/evm_circuit/execution/pop.rs
zkevm-circuits/src/evm_circuit/execution/push.rs

first we prefer to implement dummy gadgets for various error types such that failed tx can pass the circuit at the moment. after this will do real implementation for each errors defined in #597 !

dummy error gadgets

---

zkevm-circuits/src/lib.rs
zkevm-circuits/src/pi_circuit.rs
zkevm-circuits/src/test_util.rs
zkevm-circuits/src/tx_circuit.rs

according to [spec](https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/public_inputs.md)

Add Public Inputs circuit

---

zkevm-circuits/src/super_circuit.rs

copy circuit double assigned

---

zkevm-circuits/src/evm_circuit/execution.rs

fix empty block assigning error

---

zkevm-circuits/src/bytecode_circuit/dev.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/keccak_circuit/keccak_bit.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/table.rs
zkevm-circuits/src/tx_circuit.rs
zkevm-circuits/src/tx_circuit/sign_verify.rs

Connect Keccak circuit and table

---

.github/integrationTestsScripts/wakeUpRunner.sh
.github/workflows/integration.yml

With this PR a self hosted runner is implemented for Integration Tests GH Action.
Note: This action fails using GH runner, due to memory starvation.

Self hosted runner for Integration Tests GH Action

---

Cargo.lock
bus-mapping/Cargo.toml
bus-mapping/src/circuit_input_builder.rs
bus-mapping/src/circuit_input_builder/block.rs
bus-mapping/src/mock.rs
circuit-benchmarks/Cargo.toml
eth-types/Cargo.toml
eth-types/src/geth_types.rs
eth-types/src/lib.rs
integration-tests/Cargo.toml
integration-tests/src/bin/gen_blockchain_data.rs
mock/Cargo.toml
mock/src/block.rs
mock/src/transaction.rs
zkevm-circuits/Cargo.toml
zkevm-circuits/src/test_util.rs

upgrade ethers-* packages to 0.17.0

---

Cargo.lock
circuit-benchmarks/src/copy_circuit.rs
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/evm_circuit.rs
zkevm-circuits/src/super_circuit.rs
zkevm-circuits/src/table.rs
zkevm-circuits/src/witness/tx.rs

The CopyCircuit was not using the Value API for witness assignation.
Therefore, the Challenge API has been integrated in both `configure` and
`synthesize` steps and the `Value<F>` is the default operand.
Resolves: #955

CopyCircuit Challenge API integration

---

bus-mapping/src/evm/opcodes/balance.rs

fix balance test

---

zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs

fix issue #1004 , and internal test for jumpi error.

fix issue #1004 

---

zkevm-circuits/src/evm_circuit/execution/logs.rs

when is_persistent false, current copy_rwc_inc should assign with zero.  also add false persistent cases.

fix log copyrwc when is_persistent = false

---

CONTRIBUTING.md
bus-mapping/README.md
geth-utils/README.md
testool/README.md

Fix: typos

---

zkevm-circuits/src/evm_circuit/util.rs

chore: fix typo

---

zkevm-circuits/src/pi_circuit.rs

Add a `gen_rand_rpi` function to commit to the `raw_public_inputs_col` values used in Pi circuit.

add gen_rand_rpi for pi circuit

---

zkevm-circuits/src/evm_circuit/param.rs

Remove unused constant N_CELLS_STEP_STATE to increase readability.

Remove unused constant N_CELLS_STEP_STATE

---

zkevm-circuits/src/evm_circuit/execution/sstore.rs

Constrain SSTORE with gas reentrancy sentry. Gas reentrancy sentry could be referenced in [this go-ethereum code](https://github.com/ethereum/go-ethereum/blob/master/core/vm/operations_acl.go#L30).
Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1214
- [_item_]
Could be tested with previous SSTORE gadget test cases.
<hr>
```
This …
```

fix: add a constraint for SSTORE gas reentrancy sentry

---

bus-mapping/src/state_db.rs

current Account::is_empty is not correct. Fix it to be consistent with [EIP158](https://eips.ethereum.org/EIPS/eip-158).  This will not affect real world use cases, but i remember this bug causes several testool cases fail. (These patches are picked from scroll fork, so it is difficult for me to recall which exact cases will be fixed by this PR since it is a long time i fixed them...)
this PR will also fix the (2) problem in https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1118
- [_item_]
<hr>
The target readers could be future developers, reviewers, and auditors. By reading your description, they should easily understand the changes proposed in this pull …

fix account empty

---

eth-types/src/evm_types.rs
eth-types/src/evm_types/stack.rs
zkevm-circuits/src/evm_circuit/execution/extcodehash.rs
zkevm-circuits/src/evm_circuit/execution/push.rs
zkevm-circuits/src/evm_circuit/execution/return_revert.rs
zkevm-circuits/src/test_util.rs

[_PR description_]
- [_item_]
<hr>
```
```
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information that could help reviewers to …

fix some typos and outdated namings

---

zkevm-circuits/src/root_circuit.rs

Add derive(Clone) to the RootCircuit.
This is required by zkevm-chain.

feat: RootCircuit: add derive(Clone)

---

bus-mapping/src/evm/opcodes/calldatacopy.rs
bus-mapping/src/evm/opcodes/codecopy.rs
bus-mapping/src/evm/opcodes/extcodecopy.rs
bus-mapping/src/evm/opcodes/returndatacopy.rs
eth-types/src/evm_types/memory.rs

the memory copy codes in calldatacopy/returndatacopy/(ext)codecopy are almost identical. So use a unified function to reduce repeated codes.
- [_item_]
<hr>
```
```
- What …

refactor duplicated memory copy codes

---

zkevm-circuits/src/keccak_circuit.rs
zkevm-circuits/src/keccak_circuit/cell_manager.rs
zkevm-circuits/src/keccak_circuit/keccak_packed_multi.rs

Make methods private in keccak cell manager and clean some unused calls
No issue
run tests

Make methods private in keccak cell manager and clean some unused calls

---

zkevm-circuits/src/keccak_circuit.rs

Keccak circuit annotations
Closes https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1106
- Keccak circuit annotations
Because annotations make the world a better place
Compiles.

Keccak circuit annotations

---

integration-tests/src/integration_test_circuits.rs
integration-tests/tests/circuits.rs

ExpCircuit integration test
Closes https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1100
- ExpCircuit integration test
For fun and profit
Running integration tests

ExpCircuit integration test

---

zkevm-circuits/src/evm_circuit/util/math_gadget/mul_add_words.rs

Fix a typo found by another community developer
N/A
N/A
N/A

fix a typo in comment

---

zkevm-circuits/src/evm_circuit/execution/begin_tx.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_constant.rs

Fix issue #1192 
Issue #1192
- [_item_]
<hr>
```
```
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information that could help reviewers to think …

create tx by mock crate

---

zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/table.rs

Support word lo-hi for copy circuit
Address #1384
- Change the column id to word lo hi columns

[word lo/hi] Copy circuit

---

zkevm-circuits/src/evm_circuit/execution/end_tx.rs

Enable tests to check if gas refund was implemented correctly (c.f. [EIP 3529](https://eips.ethereum.org/EIPS/eip-3529))
Issue #1111 
- Uncommenting and updating tests
Using the commented values and common values for account creation.

Re-enable end_tx tests that depended on SSTORE

---

.github/workflows/ci.yml
zkevm-circuits/src/copy_circuit.rs
zkevm-circuits/src/super_circuit/test.rs

retain all test
Close https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1478
- retain/rollback ci.yml workaround changes
- fix copy circuit unittest

[word lo/hi] retain ci test on word-lo-hi branch on all subcircuit

---

zkevm-circuits/src/bin/stats/main.rs

Add overall summary for cell utilization
N/A
- sum of `available_cells`
- sum of `unused_cells`
- Utilization `#unused_cells`/`#available_cells`
```
Main:
+-----------------------------------+------------------------------+-------------------------+
| "storage_1" total_available_cells | "storage_1" total_used_cells | "storage_1" Utilization (%) |
+-----------------------------------+------------------------------+-------------------------+
| 25480                             | 6482                         | 25.4                    |
+-----------------------------------+------------------------------+-------------------------+
Word-lo-hi
+-----------------------------------+------------------------------+-----------------------------+
| "storage_1" total_available_cells | "storage_1" …
```

add overall cell utilization statistics

---

.github/testoolScripts/build.sh
.github/testoolScripts/cleanup.sh
.github/testoolScripts/prepare.sh
.github/testoolScripts/run.sh
.github/testoolScripts/sync.sh
.github/testoolScripts/wakeUpRunner.sh
.github/workflows/testool.yml

This PR introduces testool nightly builds in GH Actions. The workflow can also be triggered manually selecting between light and nightly suites.
The reports are public now under: http://testool-public.s3-website.eu-central-1.amazonaws.com/
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1505
Executed manually and automatically the workflow, triggering both suites.

Testool migration

---

zkevm-circuits/src/evm_circuit/execution/error_code_store.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_creation_code.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_opcode.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_account_access.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_call.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_constant.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_exp.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_log.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_memory_copy.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_sha3.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_sload_sstore.rs
zkevm-circuits/src/evm_circuit/execution/error_oog_static_memory.rs
zkevm-circuits/src/evm_circuit/execution/error_return_data_oo_bound.rs
zkevm-circuits/src/evm_circuit/execution/error_stack.rs
zkevm-circuits/src/evm_circuit/util/common_gadget.rs

refactor  rw counter delta for CommonErrorGadget
#1576

feat/#1576 refactor rw counter delta for CommonErrorGadget

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs

ErrDepth can happen for all 4 callop opcodes.
- [_item_]
<hr>
```
```
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information …

fix ErrDepth check

---

testool/src/statetest/spec.rs
zkevm-circuits/src/util/word.rs
zkevm-circuits/src/witness/rw.rs

These warning messages are pretty annoying. Let's fix them.

Fix doc warnings

---

bus-mapping/src/circuit_input_builder/input_state_ref.rs

current codes try to get offet/len inside handle_restore_context for return/revert. When a stack underflow happens, parsing trace will fail.
This pr can fix testool `returndatacopy_after_failing_callcode_d0_g0_v0`
- [_item_]
<hr>
```
- …
```

fix return revert stack underflow

---

Makefile
mpt-witness-generator/trie/proof.go
mpt-witness-generator/trie/stacktrie.go

chore : typo fix

---

zkevm-circuits/src/bin/stats/helpers.rs
zkevm-circuits/src/bin/stats/main.rs

- add create/create2 in stats
- in stats, separate dynamic gas with constant gas
- sort by height per constant gas to derive worst case

chores: add create/create2 in stats

---

integration-tests/build.rs

Change integration-tests/build.rs to fetch OZ submodule automatically.
I propose to change [integration-tests/build.rs](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/integration-tests/build.rs) to automatically fetch OZ contracts submodule, so that initial rust-analyzer indexation works without errors. Right now it's necessary to fetch the submodule manually or by running [integration-tests/run.sh](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/integration-tests/run.sh).
This feature is hard to test neither with unit-tests nor with integration-tests, so it was tested locally, on a new & clean repo and worked without any errors.
A completed spawned process returns its `exit-status`/code, so possibly it's a good tone to check if it's …

chore(integration-tests): change build.rs to pull submodules

---

mock/src/test_ctx2.rs

fix typos in test_ctx2.rs

---

mpt-witness-generator/oracle/preimage.go
mpt-witness-generator/state/state_object.go
mpt-witness-generator/state/statedb.go
mpt-witness-generator/witness/branch.go

Find few typos while studying the code, in comments. Hope I can be of any help, even if tiny.
Have a nice weekend.

chore(mpt-witness-generator): bit of proofreading

---

bus-mapping/src/operation.rs
zkevm-circuits/src/evm_circuit/table.rs
zkevm-circuits/src/table/rw_table.rs

Adds a comment so that it makes it clear what is RwTableTag when going through the code.

Add comment regarding RwTableTag

---

zkevm-circuits/src/bytecode_circuit.rs
zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/evm_circuit/execution/error_invalid_jump.rs
zkevm-circuits/src/evm_circuit/util/math_gadget/test_util.rs

chore: fix typos

---

zkevm-circuits/src/evm_circuit/execution.rs
zkevm-circuits/src/keccak_circuit.rs
zkevm-circuits/src/test_util.rs
zkevm-circuits/src/witness/block.rs

chore: fix some typos
